### PR TITLE
Bump boost version to 1.55 in CMake build

### PR DESCRIPTION
**Pull request by willyd**
As mentioned in #5400

### CODE REVIEW

**Comment by willyd** [comment]
CMake currently requires 1.46
Travis installs 1.54
Documentation requires 1.55

Should settle for 1.54 everywhere or update travis build to match the requirement?

**Comment by shelhamer** [comment]
I'm perfectly happy with requiring 1.54 or 1.55 everywhere. Let's pick 1.55?

**Comment by willyd** [comment]
@shelhamer Ok great. Can you get the Travis build to install 1.55 or point me to what I should change and where?

**Comment by shelhamer** [comment]
The dependencies for travis are handled by install-deps.sh and boost can be found here: https://github.com/BVLC/caffe/blob/master/scripts/travis/install-deps.sh#L12-L15

For trusty, I believe there are packages for boost 1.55 in particular but I don't know the names offhand. Could you have a look?

**Comment by willyd** [comment]
Ok thanks. I'll see what I can find.

**Comment by willyd** [comment]
@shelhamer I updated the Travis dependencies to 1.55 so this should be good to go.

**Comment by shelhamer** [comment]
Thanks @willyd! 👍

**Comment by pjreed** [comment]
For reference, this breaks compatibility with [ROS Indigo](http://wiki.ros.org/indigo) on Ubuntu 14.04 because it's linked against boost 1.54.  If I manually edit `cmake/Dependencies.cmake` to require 1.54, Caffe seems to compile without any problems.

**Comment by willyd** [comment]
I wouldn't mind requiring 1.54 instead of 1.55 since it seems that this is what was used by default on the Travis build before this change went in. As mentioned the referenced issue. For me, 1.53+ is sufficient. I will let it to @shelhamer to decide if we should switch back to 1.54.

**Comment by lukeyeager** [comment]
Please switch back to 1.54. That is the version [packaged for](http://packages.ubuntu.com/source/trusty/boost-defaults) Ubuntu 14.04. This change broke our DIGITS builds: https://travis-ci.org/NVIDIA/DIGITS/jobs/231102340.

**Comment by shelhamer** [comment]
I'm completely fine with switching back to 1.54—I didn't realize compatibility with Ubuntu 14.04 was lost with this switch.

**Comment by wilsonge** [comment]
For what it's worth Centos 7 includes Boost 1.53 - is it "OK" to drop compatibility with that too?

**Pull request merged**
