### PR TITLE
fix bugs by adding const

### PR DESCRIPTION
**Pull request by xianjiec**
fix bugs by adding const to enable make matcaffe

### CODE REVIEW

**Comment by jeffdonahue** [comment]
Thanks @xianjiec! (Presumably #1686 broke this -- PRs to add matcaffe to our Travis build to prevent things like this from happening in the future are definitely welcome...)

**Comment by jeffdonahue** [comment]
Hm, was about to merge but looks like the Python tests are failing? @longjon any idea why? Can't imagine it's actually related to the matcaffe changes...

**Comment by jeffdonahue** [comment]
Ok, I see now that the Python tests were failing at the merge of the PR adding those (https://travis-ci.org/BVLC/caffe/jobs/47889332), so I'll merge this.

**Comment by shelhamer** [comment]
This is my fault -- I forgot to update the Python tests in the back-merge that brought #1728 to dev. I'll fix it. Another reason to do away with dual branches...

**Pull request merged**
