### PR TITLE
Refactor solvers regularization and logging code

### PR DESCRIPTION
**Pull request by cypof**
Update: changed description to "refactor"

### CODE REVIEW

**Comment by flx42** [comment]
Maybe "refactor" instead of "deduplicate"?

**Comment by cypof** [comment]
More precise type of refactoring? :)

**Comment by flx42** [comment]
I think "deduplication" is usually used for data, not for code. But I might be wrong :)

**Comment by shelhamer** [comment]
Adapted and merged in #2518. Thanks for this @cypof!

**Pull request closed without merging**
