### PR TITLE
Fixes https://github.com/BVLC/caffe/issues/4046

### LINKED ISSUE #4046: Compiling with CUDA on Ubuntu 16.04 + Solution
Compiling on a clean install of Ubuntu 16.04 with cmake and using CUDA from the repo. 

I get the following error:

`/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n; 
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at cuda_compile_generated_sgd_solver.cu.o.cmake:266 (message):
  Error generating file
  /opt/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_sgd_solver.cu.o
`
Seems TensorFlow has similar issues: https://github.com/fayeshine/tensorflow/commit/6c8c572c12521d706eda692fa7793f90b45dde20

By adding that flag to my CMakeLists.txt it fixed the problem and compiles fine. ie. Add this near the front:
set(${CMAKE_CXX_FLAGS} "-D_FORCE_INLINES ${CMAKE_CXX_FLAGS}")

Someone might be able to add this to the cmake file.

### PR DESCRIPTION
**Pull request by kleinric**
Allows compilation on Ubuntu 16.04 using CMake and CUDA. Fixes #4046

### CODE REVIEW

**Comment by kleinric** [comment]
This could possibly be fine-tuned to only apply the -D_FORCE_INLINES flags for the specific files that need it, rather than the entire repo. But I'm not sure where these changes may need to go.

**Comment by lukeyeager** [comment]
Protip: use the phrase "Fixes #4046" in your commit message instead of "Fixes BVLC#4046" if you want to close the other bug automatically.

Or put it in the body of the first post in this PR. That's how I prefer to do it.

**Comment by kleinric** [comment]
Thanks, I actually copied the entire github url in the commit message. Github
seems to have parsed it out itself. This is the first time I've done a pull
request, so not really sure how it all works yet :P

On Apr 26 2016, at 6:29 pm, Luke Yeager &lt;notifications@github.com&gt;
wrote:  

> Protip: use the phrase "Fixes
[#4046](https://github.com/BVLC/caffe/issues/4046)" in your commit message
instead of "Fixes [BVLC#4046](https://github.com/BVLC/caffe/issues/4046)" if
you want to close the other bug automatically.

>

> Or put it in the body of the first post in this PR. That's how I prefer to
do it.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/BVLC/ca
ffe/pull/4047#issuecomment-214802189)

**Comment by lukeyeager** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages
https://github.com/blog/1506-closing-issues-via-pull-requests

Example: https://github.com/BVLC/caffe/pull/3731

**Comment by shelhamer** [comment]
Thanks for submitting a fix, but this was addressed upstream by CUDA 8 as concluded in #4046.

**Pull request closed without merging**
