### PR TITLE
add BLAS option for basic BLAS library

### PR DESCRIPTION
**Pull request by cdluminate**
As explained in #2601 , Debian/Ubuntu has a feature called `alternative` so in these distributions caffe can be built against the reference BLAS library (`libblas-dev`), and run against atlas or openblas as long as user alter the symbol links.

The same change is applied downstream in the Debian packaging, but this pull request is a bit different from the Debian patch.
http://anonscm.debian.org/cgit/debian-science/packages/caffe.git/tree/debian/patches/cmake-using-basic-blas

In downstream I make "generic" as the default, while in this PR I do not touch the default BLAS.
However this option should not be exposed to normal users, as the basic BLAS may cause trouble to numpy.

Detail:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823140

### CODE REVIEW

**Comment by lukeyeager** [comment]
While you're messing with this, it would be great if you could set up CMake to pick the best library available, if none is selected. It seems to me that it should always pick OpenBLAS over ATLAS, if both are available.

Also, I expect that the @BVLC team will ask you to implement this for the raw Makefile build as well before merging.

**Comment by CDLuminate** [comment]
@lukeyeager 

I had a rethink. Since this change is somewhat Debian-specific, It's OK for me to keep it at downstream. Making upstream Caffe compilable against `generic BLAS` won't provide much help.

The dependency of updated caffe package is `libblas3 | libblas.so.3`, I need to remind users to install openblas or atlas before installing caffe to avoid caffe from running against generic BLAS.
However it is wonderful that in the alternatives system OpenBLAS enjoys the highest priority among those BLAS's, so under default mode openblas will be the one when user had both openblas and atlas installed.
```
$ sudo update-alternatives --display libblas.so
libblas.so - auto mode
  link currently points to /usr/lib/openblas-base/libblas.so
/usr/lib/atlas-base/atlas/libblas.so - priority 35
  slave blas.pc: /usr/lib/pkgconfig/blas-atlas.pc
  slave libblas.a: /usr/lib/atlas-base/atlas/libblas.a
/usr/lib/libblas/libblas.so - priority 10
  slave blas.pc: /usr/lib/pkgconfig/blas-netlib.pc
  slave libblas.a: /usr/lib/libblas/libblas.a
/usr/lib/openblas-base/libblas.so - priority 40
  slave blas.pc: /usr/lib/pkgconfig/blas-openblas.pc
  slave libblas.a: /usr/lib/openblas-base/libblas.a
Current 'best' version is '/usr/lib/openblas-base/libblas.so'.

$ sudo update-alternatives --display libblas.so.3
libblas.so.3 - auto mode
  link currently points to /usr/lib/openblas-base/libblas.so.3
/usr/lib/atlas-base/atlas/libblas.so.3 - priority 35
  slave libblas.so.3gf: /usr/lib/atlas-base/atlas/libblas.so.3
/usr/lib/libblas/libblas.so.3 - priority 10
  slave libblas.so.3gf: /usr/lib/libblas/libblas.so.3
/usr/lib/openblas-base/libblas.so.3 - priority 40
  slave libblas.so.3gf: /usr/lib/openblas-base/libblas.so.3
Current 'best' version is '/usr/lib/openblas-base/libblas.so.3'.
```

**Comment by lukeyeager** [comment]
Sure, but when Caffe chooses to build against ATLAS it links to `libatlas.so.3` directly - not to `libblas.so`. Caffe bypasses the alternatives system.

##### My configuration
```sh
$ update-alternatives --display libblas.so
libblas.so - auto mode
  link best version is /usr/lib/openblas-base/libblas.so
  link currently points to /usr/lib/openblas-base/libblas.so
  link libblas.so is /usr/lib/libblas.so
  slave blas.pc is /usr/lib/pkgconfig/blas.pc
  slave libblas.a is /usr/lib/libblas.a
/usr/lib/atlas-base/atlas/libblas.so - priority 35
  slave blas.pc: /usr/lib/pkgconfig/blas-atlas.pc
  slave libblas.a: /usr/lib/atlas-base/atlas/libblas.a
/usr/lib/libblas/libblas.so - priority 10
  slave blas.pc: /usr/lib/pkgconfig/blas-netlib.pc
  slave libblas.a: /usr/lib/libblas/libblas.a
/usr/lib/openblas-base/libblas.so - priority 40
  slave blas.pc: /usr/lib/pkgconfig/blas-openblas.pc
  slave libblas.a: /usr/lib/openblas-base/libblas.a
```
##### Building with no `-DBLAS` flag
```sh
$ cmake ..
# ...
--   BLAS              :   Yes (Atlas)
# ...

$ make
# ...

$ ldd tools/caffe | grep las
	libcblas.so.3 => /usr/lib/libcblas.so.3 (0x00007fd11df33000)
	libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007fd1179cc000)
```
##### Building with `-DBLAS=Open`
```sh
$ cmake .. -DBLAS=Open
# ...
--   BLAS              :   Yes (Open)
# ...

$ make
# ...

$ ldd tools/caffe | grep las
	libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007f66b751e000)
```

Am I missing something? Does it link to `libblas.so.3` for you?

**Comment by CDLuminate** [comment]
@lukeyeager 

You are absolutely right.

By default caffe links Atlas and bypasses libblas.so, and the same when selected openblas.
That's because the `FindOpenBLAS` and the `FindAtlas` package directly send the true library to the linker. In order to link caffe against `libblas.so`, there must be some module to substitute `FindOpenBLAS` and `FindAtlas`, and at this point `FindBLAS` is the right choice again.

**Comment by CDLuminate** [comment]
Makefile support may seem like this (around line `352 # BLAS configuration (default = ATLAS)`)
```
else ifeq ($(BLAS), generic)
    LIBRARIES += blas
else ...
```

**Comment by lukeyeager** [comment]
FYI, just for kicks I tried configuring like this: `cmake .. -DBLAS=alskj`. It reported a successful configuration and the build failed at link time (after compilation). It'd be nice if it threw an error for invalid values.

**Comment by lukeyeager** [comment]
This is strange. Why is it still linking against OpenBLAS?
```sh
$ cmake .. -DBLAS=Generic -DCPU_ONLY=On
$ make -j12
$ ldd tools/caffe | grep las
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f0039687000)
	libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007f003162a000)
```

**Comment by CDLuminate** [comment]
compile this C source
```
int main(void) { return 0; }
```
with this command line:
```
$ gcc a.c -lblas
```

My alternative `libblas.so` is pointed to openblas, and the result is similar to your compilation:
```
$ ldd a.out 
	linux-vdso.so.1 (0x00007ffcfd5f1000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fdf5cfbe000)                             <-----
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdf5cc13000)
	libopenblas.so.0 => /usr/lib/libopenblas.so.0 (0x00007fdf5ad6d000)            <-----
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdf5aa6c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdf5a84f000)
	libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007fdf5a531000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fdf5d21d000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007fdf5a2f4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdf5a0de000)
```

**Comment by CDLuminate** [comment]
But take it easy, ldd finds recursive dependencies too.

You should check linkage with this command line actually:
```
$ readelf -d a.out 

Dynamic section at offset 0x808 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x4004d8
 0x000000000000000d (FINI)               0x4006b4
 0x0000000000000019 (INIT_ARRAY)         0x6007f0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x6007f8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400260
 0x0000000000000005 (STRTAB)             0x4003a0
 0x0000000000000006 (SYMTAB)             0x400298
 0x000000000000000a (STRSZ)              179 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x6009f0
 0x0000000000000002 (PLTRELSZ)           48 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x4004a8
 0x0000000000000007 (RELA)               0x400490
 0x0000000000000008 (RELASZ)             24 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x400470
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x400454
 0x0000000000000000 (NULL)               0x0
```

Yeah, all clean, nothing strange.
:-)

**Comment by CDLuminate** [comment]
Here are more examples:
```
$ readelf -d /usr/bin/caffe

Dynamic section at offset 0x18900 contains 35 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libcaffe.so.1.0.0-rc3]
 0x0000000000000001 (NEEDED)             Shared library: [libboost_system.so.1.55.0]
 0x0000000000000001 (NEEDED)             Shared library: [libglog.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgflags.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libboost_python-py27.so.1.55.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x8080
```

```
$ readelf -d /usr/lib/x86_64-linux-gnu/libcaffe.so.1.0.0-rc3 

Dynamic section at offset 0x369770 contains 46 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libboost_system.so.1.55.0]
 0x0000000000000001 (NEEDED)             Shared library: [libboost_thread.so.1.55.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libglog.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgflags.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libprotobuf.so.9]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_serial_hl.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [libhdf5_serial.so.8]
 0x0000000000000001 (NEEDED)             Shared library: [liblmdb.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libleveldb.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_core.so.2.4]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_highgui.so.2.4]
 0x0000000000000001 (NEEDED)             Shared library: [libopencv_imgproc.so.2.4]
 0x0000000000000001 (NEEDED)             Shared library: [libblas.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libpython2.7.so.1.0]
 0x0000000000000001 (NEEDED)             Shared library: [libboost_python-py27.so.1.55.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libcaffe.so.1.0.0-rc3]
 0x000000000000000c (INIT)               0xe9210
```

**Comment by lukeyeager** [comment]
> But take it easy, ldd finds recursive dependencies too.

Ah good call. I knew that but hadn't thought through the implications here. Nevermind!

**Comment by cdluminate** [comment]
ping?

**Pull request closed without merging**
