### PR TITLE
Add support for vs2015

### PR DESCRIPTION
**Pull request by EnjoyLeole**
most dependencies are base on vc120(vs2013), while some of them doesn't have an vs2015 compatible version at this moment.

### CODE REVIEW

**Comment by willyd** [comment]
@EnjoyLeole Thanks for submitting this. VS 2015 is planned with the CMake build. There seems to be a lot more than just VS 2015 support in this PR though. If you really want VS 2015 support with the current VS build please cherry-pick only the needed changes. 

> most dependencies are base on vc120(vs2013), while some of them doesn't have an vs2015 compatible version at this moment.

Do you mean that not all nuget packages were updated with VS 2015 versions?

**Comment by EnjoyLeole** [comment]
@willyd  Yes, several pkgs  don't have a version for vs2015, LevelDB\boost-python2.7,etc.

**Comment by willyd** [comment]
@EnjoyLeole You can find a working (at least for CPU and Python) branch based on the current windows CMake build that works with VS 2015 at https://github.com/willyd/caffe/tree/vs2015.

**Comment by willyd** [comment]
VS 2015 support was just merged in the windows branch. The CMake build must be used.

**Pull request closed without merging**
