### PR TITLE
Openmp

### PR DESCRIPTION
**Pull request by borisgin**
Parallel version of caffe for CPU based on OpenMP. Significant speed-up on CPU .Scales well with number of cores (3x for 4 cores , 10x - for 16 cores). Modified files: constitutional , pulling and relu layers , im2col and col2im.

### CODE REVIEW

**Comment by xiaodaxia** [comment]
@borisgin    Hello, I feel a bit confused by the following benchmark.
Fixed Makefile to support openmp with MKL. Current benchmark results:
cifar10/ train_quick):
desktop Core i7-3770K CPU @ 3.50GHz × 4 cores x no HT): 100 sec
K20: 90 sec
Though I only have gtx980, but the train_quick demo finished in more than 250s. So I think
there is a misunderstanding? I think the only difference is that I used openblas/atlas instead of MKL,
but in my understanding the mkl will not affect gpu performance that much?
Does the train_quick demo always run 5000 iterations as it does now?

**Comment by forresti** [comment]
Is this PR (or something similar) going to be merged soon?

When I checked not too long ago, CPU Caffe is unnecessarily slow without OpenMP. I'm debating tacking my own OpenMP things together... but merging this PR with present-day Caffe would be optimal.

**Comment by talda** [comment]
I wouldn't hold my breath. This PR is more than a year old and it doesn't seem the maintainers think it should be merged. (probably better to close it)

**Comment by shelhamer** [comment]
While CPU execution can be further optimized this PR is closed since it is against the deprecated dev branch. This branch was not merged at the time due to concerns about further complexity and dependencies.

**Comment by bhack** [comment]
@naibaf7 It is working also on CPU at https://github.com/BVLC/caffe/pull/2610

**Comment by naibaf7** [comment]
@shelhamer @bhack 
#2610 Uses OpenCL kernels and a CPU (MKL, OpenBLAS, Atlas) BLAS.
While OpenCL might not be the best for CPUs, the Alexnet runs twice as fast on Hybrid-OpenCL (that's what I call it) than the "legacy" singlethreaded CPU branch on a quadcore CPU.

**Comment by Crefeda** [comment]
Hi, I was try to build your openmp version, on a CentOS 6.5 computer and I got a protobuf version error
my current one is libprotoc 2.4.1
could you let me know which version was compatible for you?

**Comment by borisgin** [comment]
Hi Crefeda,
Can you post a detailed error, please?
Did caffe-master branch build passed without issues?
Thanks, Boris

**Comment by Yangqing** [comment]
@Crefeda If I recall correctly, caffe relies on some features that are introduced in protobuf 2.5, so I think 2.5 and above should work.

**Pull request closed without merging**
