### PR TITLE
fix problems in net_surgery.ipynb

### PR DESCRIPTION
**Pull request by crazytan**
Hi,
I was running this notebook and I found several problems:

1. Instead of `import Image` it should be `from PIL import Image`, which is again an obsolete package. So I delete it and use `caffe.io.load_image`.
2. the comment `# set first filter bias to 10` should be `# set first filter bias to 1`.
3. `caffe` is imported again in input 7.

I corrected these small mistakes. Hope it helps!

### CODE REVIEW

**Comment by ajtulloch** [comment]
LGTM, thanks!

**Comment by longjon** [comment]
These changes look good, thanks. However, I'd prefer if you could remove irrelevant changes from the commit (e.g., object address changes), so that we maintain a clean, readable history. (And please do squash into a single commit.)

**Comment by crazytan** [comment]
Thanks for the comment! I have reverted the unnecessary changes but kept the change of output diff (I think it's because the files themselves changed).

**Comment by longjon** [comment]
Okay, thanks!

**Pull request merged**
