### PR TITLE
add layer_dict to the python interface

### PR DESCRIPTION
**Pull request by nitnelave**
Similar to the blobs map, have a layer map.

This turns 
`net.layers[list(net._layer_names).index("ip2")]`
 into 
`net.layer_dict["ip2"]`

### CODE REVIEW

**Comment by ajtulloch** [comment]
Sure, seems reasonable to me. Could you add some unit tests?

**Comment by nitnelave** [comment]
I'd be glad to, but where? :) (Sorry, it's my first time contributing to caffe, and I can't seem to find the tests)

**Comment by nitnelave** [comment]
Nevermind, I found them in python/caffe/test

**Comment by nitnelave** [comment]
Here are the tests. To check the equality of the pointed layers, I only checked the types, but since the layers of the test network are all different types anyway, it seemed reasonable.

**Pull request merged**
