### PR TITLE
Abort Makefile parsing if the configuration file cannot be found.

### PR DESCRIPTION
**Pull request by flx42**
Related to #2328

### CODE REVIEW

**Comment by longjon** [comment]
Erm, doesn't `make` already do this? This is what I get with no `Makefile.config`:
```
$ make
Makefile:4: Makefile.config: No such file or directory
make: *** No rule to make target `Makefile.config'.  Stop.
```
(This is also why the `-include` directive exists.)

I could see an argument for a friendlier message explaining `Makefile.config`, but that's not in this PR right now.

**Comment by longjon** [comment]
In fact, I can't reproduce #2328 (before the patch) unless I `make -k clean`. @flx42, do you have an alias?

**Comment by flx42** [comment]
Yes, I do have an alias for make. But this barely changes the problem IMO. The make process should be aborted asap or this can potentially lead to many troubles.

**Comment by longjon** [comment]
Okay, I agree. `Makefile.config` is effectively an implicit dependency for everything else, but right now `make -k` will happily cruise along with it.

**Comment by flx42** [comment]
Yes, and I think adding `Makefile.config` as an explicit dependency would clutter the Makefile and create cryptic error messages. Unless you have another idea, I think a solution like this one is the simpler.

**Comment by longjon** [comment]
Merged (I modified the text a little and added a comment to remind future readers why the check is necessary in caaf321a1dc6d51adb1ee0c80f76d4d172145884). Thanks @flx42!

**Pull request merged**
