### PR TITLE
Opencl intel spatial convolution optimization

### PR DESCRIPTION
**Pull request by gongzg**
This PR is mainly for the spatial convolution kernel optimization. The convolution performance for 11x11 kernel size got about 50% boost and other layers get slightly improvement.

### CODE REVIEW

**Comment by gongzg** [comment]
@naibaf7 please help to review, thx.

**Comment by naibaf7** [comment]
@gongzg 
Nice! I'm also going to release a next version of libDNN convolutions this week with up to 100% boost. But I have no idea how they perform on Intel iGPUs... probably not as well as yours since yours are especially optimized for those chips.
But a test would be nice. What chips do you test on?

**Comment by gongzg** [comment]
@naibaf7 I'm using a BDW GT2 notebook.

**Comment by naibaf7** [comment]
@gongzg 
Would it be possible to get remote access (SSH + X11-forwarding) to such a machine at one point? I don't have broadwell or skylake GPUs available for testing yet.

**Comment by ngaloppo** [comment]
@naibaf7 we're working on your request

**Comment by ngaloppo** [comment]
@naibaf7 Someone will contact you soon (if not already) about getting you a system for testing & development.

**Pull request merged**
