### PR TITLE
data transform parallel excution for batch

### PR DESCRIPTION
**Pull request by ttagu99**
The data augmentation transform performed a bottleneck in training time.
So I changed the transform processing to parallel execution.

### CODE REVIEW

**Comment by antran89** [comment]
@ttagu99 It seems to be a good improvement. Is there any comparisons with the original implementations.

**Comment by ttagu99** [comment]
My pc environment is i7-5820K,32G Ram, GTX 1080 * 2.
In my case, train batch was about twice as fast.
1.5 times faster in test batch.


I0203 07:49:27.883797  9028 caffe.cpp:218] Using GPUs 0, 1
I0203 07:49:27.933800  9028 caffe.cpp:223] GPU 0: GeForce GTX 1080
I0203 07:49:27.934800  9028 caffe.cpp:223] GPU 1: GeForce GTX 1080
---- Train Phase Input -----
layer {
  name: "train-data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
  mirror: true
  flip_hor: true
  crop_size: 544
  crop_offset_rand: true
  mean_file: "CAR_DIST/train.binaryproto"
  contrast_adjustment: true
  smooth_filtering: true
  jpeg_compression: true
  rotation_angle_interval: 0
  display: false
  }
  data_param {
    source: "CAR_DIST/Train_out/"
    batch_size: 10
    backend: LMDB
  }
}

- AS IS - 
I0203 08:19:05.465469  7112 data_layer.cpp:102] Prefetch batch: 981 ms.
I0203 08:19:05.466470  7112 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:05.466470  7112 data_layer.cpp:104] Transform time: 979.056 ms.
I0203 08:19:06.458526  7112 data_layer.cpp:102] Prefetch batch: 987 ms.
I0203 08:19:06.458526  7112 data_layer.cpp:103]      Read time: 2 ms.
I0203 08:19:06.458526  7112 data_layer.cpp:104] Transform time: 984.056 ms.
I0203 08:19:06.525530  5752 data_layer.cpp:102] Prefetch batch: 1056 ms.
I0203 08:19:06.526530  5752 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:06.526530  5752 data_layer.cpp:104] Transform time: 1055.06 ms.
I0203 08:19:07.658596  5752 data_layer.cpp:102] Prefetch batch: 1126 ms.
I0203 08:19:07.658596  5752 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:19:07.658596  5752 data_layer.cpp:104] Transform time: 1126.07 ms.
I0203 08:19:07.917609  7112 data_layer.cpp:102] Prefetch batch: 1095 ms.
I0203 08:19:07.918609  7112 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:07.918609  7112 data_layer.cpp:104] Transform time: 1093.06 ms.
I0203 08:19:08.767658  5752 data_layer.cpp:102] Prefetch batch: 1103 ms.
I0203 08:19:08.767658  5752 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:19:08.767658  5752 data_layer.cpp:104] Transform time: 1103.06 ms.
I0203 08:19:09.209683  7112 data_layer.cpp:102] Prefetch batch: 1285 ms.
I0203 08:19:09.209683  7112 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:09.209683  7112 data_layer.cpp:104] Transform time: 1283.07 ms.
I0203 08:19:10.050731  5752 data_layer.cpp:102] Prefetch batch: 1277 ms.
I0203 08:19:10.050731  5752 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:10.050731  5752 data_layer.cpp:104] Transform time: 1276.07 ms.
I0203 08:19:10.134737  7112 data_layer.cpp:102] Prefetch batch: 919 ms.
I0203 08:19:10.135736  7112 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:19:10.135736  7112 data_layer.cpp:104] Transform time: 918.052 ms.
I0203 08:19:11.005786  5752 data_layer.cpp:102] Prefetch batch: 949 ms.
I0203 08:19:11.006786  5752 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:11.006786  5752 data_layer.cpp:104] Transform time: 947.054 ms.
I0203 08:19:11.073791  7112 data_layer.cpp:102] Prefetch batch: 930 ms.
I0203 08:19:11.073791  7112 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:19:11.073791  7112 data_layer.cpp:104] Transform time: 928.053 ms.
I0203 08:19:12.024844  5752 data_layer.cpp:102] Prefetch batch: 1013 ms.
I0203 08:19:12.024844  5752 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:19:12.025845  5752 data_layer.cpp:104] Transform time: 1012.06 ms.

- TO BE - 
I0203 07:52:33.757429  5692 data_layer.cpp:109] Prefetch batch: 467 ms.
I0203 07:52:33.757429  5692 data_layer.cpp:110]      Read time: 117.51 ms.
I0203 07:52:33.757429  5692 data_layer.cpp:111] Transform time: 349.49 ms.
I0203 07:52:33.964442  9580 data_layer.cpp:109] Prefetch batch: 774 ms.
I0203 07:52:33.964442  9580 data_layer.cpp:110]      Read time: 69.523 ms.
I0203 07:52:33.964442  9580 data_layer.cpp:111] Transform time: 704.477 ms.
I0203 07:52:34.626478  5692 data_layer.cpp:109] Prefetch batch: 336 ms.
I0203 07:52:34.626478  5692 data_layer.cpp:110]      Read time: 54.1316 ms.
I0203 07:52:34.626478  5692 data_layer.cpp:111] Transform time: 281.868 ms.
I0203 07:52:34.772487  9580 data_layer.cpp:109] Prefetch batch: 626 ms.
I0203 07:52:34.772487  9580 data_layer.cpp:110]      Read time: 35.1202 ms.
I0203 07:52:34.772487  9580 data_layer.cpp:111] Transform time: 590.88 ms.
I0203 07:52:35.629536  9580 data_layer.cpp:109] Prefetch batch: 674 ms.
I0203 07:52:35.629536  9580 data_layer.cpp:110]      Read time: 54.404 ms.
I0203 07:52:35.629536  9580 data_layer.cpp:111] Transform time: 619.596 ms.
I0203 07:52:35.945554  5692 data_layer.cpp:109] Prefetch batch: 536 ms.
I0203 07:52:35.945554  5692 data_layer.cpp:110]      Read time: 15.8207 ms.
I0203 07:52:35.945554  5692 data_layer.cpp:111] Transform time: 520.179 ms.
I0203 07:52:36.508586  9580 data_layer.cpp:109] Prefetch batch: 697 ms.
I0203 07:52:36.508586  9580 data_layer.cpp:110]      Read time: 65.6624 ms.
I0203 07:52:36.508586  9580 data_layer.cpp:111] Transform time: 631.338 ms.
I0203 07:52:36.883607  5692 data_layer.cpp:109] Prefetch batch: 770 ms.
I0203 07:52:36.883607  5692 data_layer.cpp:110]      Read time: 22.1525 ms.
I0203 07:52:36.883607  5692 data_layer.cpp:111] Transform time: 747.848 ms.
I0203 07:52:37.367635  9580 data_layer.cpp:109] Prefetch batch: 676 ms.
I0203 07:52:37.367635  9580 data_layer.cpp:110]      Read time: 92.2967 ms.
I0203 07:52:37.367635  9580 data_layer.cpp:111] Transform time: 583.703 ms.
I0203 07:52:37.443640  5692 data_layer.cpp:109] Prefetch batch: 553 ms.
I0203 07:52:37.443640  5692 data_layer.cpp:110]      Read time: 42.9682 ms.
I0203 07:52:37.443640  5692 data_layer.cpp:111] Transform time: 510.032 ms.
I0203 07:52:37.930667  5692 data_layer.cpp:109] Prefetch batch: 316 ms.
I0203 07:52:37.931668  5692 data_layer.cpp:110]      Read time: 84.6602 ms.
I0203 07:52:37.931668  5692 data_layer.cpp:111] Transform time: 231.34 ms.


---- Test Phase Input -----
layer {
  name: "val-data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    crop_size: 544
    mean_file: "CAR_DIST/validation.binaryproto"
  }
  data_param {
    source: "CAR_DIST/Validation_out/"
    batch_size: 8
    backend: LMDB
  }
}

- AS IS - 
I0203 08:04:02.267809  6324 data_layer.cpp:102] Prefetch batch: 208 ms.
I0203 08:04:02.267809  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:02.267809  6324 data_layer.cpp:104] Transform time: 208.012 ms.
I0203 08:04:02.479821  6324 data_layer.cpp:102] Prefetch batch: 207 ms.
I0203 08:04:02.479821  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:02.480821  6324 data_layer.cpp:104] Transform time: 207.011 ms.
I0203 08:04:02.692834  6324 data_layer.cpp:102] Prefetch batch: 208 ms.
I0203 08:04:02.692834  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:02.692834  6324 data_layer.cpp:104] Transform time: 208.012 ms.
I0203 08:04:02.906847  6324 data_layer.cpp:102] Prefetch batch: 208 ms.
I0203 08:04:02.906847  6324 data_layer.cpp:103]      Read time: 1 ms.
I0203 08:04:02.906847  6324 data_layer.cpp:104] Transform time: 207.012 ms.
I0203 08:04:03.119858  6324 data_layer.cpp:102] Prefetch batch: 208 ms.
I0203 08:04:03.120858  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:03.120858  6324 data_layer.cpp:104] Transform time: 208.012 ms.
I0203 08:04:03.332870  6324 data_layer.cpp:102] Prefetch batch: 207 ms.
I0203 08:04:03.332870  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:03.332870  6324 data_layer.cpp:104] Transform time: 206.012 ms.
I0203 08:04:03.547883  6324 data_layer.cpp:102] Prefetch batch: 210 ms.
I0203 08:04:03.548882  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:03.548882  6324 data_layer.cpp:104] Transform time: 210.012 ms.
I0203 08:04:03.761895  6324 data_layer.cpp:102] Prefetch batch: 209 ms.
I0203 08:04:03.761895  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:03.762895  6324 data_layer.cpp:104] Transform time: 209.012 ms.
I0203 08:04:03.975908  6324 data_layer.cpp:102] Prefetch batch: 208 ms.
I0203 08:04:03.975908  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:03.975908  6324 data_layer.cpp:104] Transform time: 208.012 ms.
I0203 08:04:04.188920  6324 data_layer.cpp:102] Prefetch batch: 208 ms.
I0203 08:04:04.188920  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:04.188920  6324 data_layer.cpp:104] Transform time: 208.012 ms.
I0203 08:04:04.402931  6324 data_layer.cpp:102] Prefetch batch: 209 ms.
I0203 08:04:04.402931  6324 data_layer.cpp:103]      Read time: 0 ms.
I0203 08:04:04.402931  6324 data_layer.cpp:104] Transform time: 208.012 ms.

- TO BE - 
I0203 07:50:14.285451  7460 data_layer.cpp:109] Prefetch batch: 144 ms.
I0203 07:50:14.285451  7460 data_layer.cpp:110]      Read time: 4.81306 ms.
I0203 07:50:14.285451  7460 data_layer.cpp:111] Transform time: 139.187 ms.
I0203 07:50:14.474462  7460 data_layer.cpp:109] Prefetch batch: 183 ms.
I0203 07:50:14.474462  7460 data_layer.cpp:110]      Read time: 17.3846 ms.
I0203 07:50:14.474462  7460 data_layer.cpp:111] Transform time: 165.615 ms.
I0203 07:50:14.623471  7460 data_layer.cpp:109] Prefetch batch: 143 ms.
I0203 07:50:14.623471  7460 data_layer.cpp:110]      Read time: 3.61339 ms.
I0203 07:50:14.623471  7460 data_layer.cpp:111] Transform time: 139.387 ms.
I0203 07:50:14.773479  7460 data_layer.cpp:109] Prefetch batch: 144 ms.
I0203 07:50:14.774479  7460 data_layer.cpp:110]      Read time: 6.43539 ms.
I0203 07:50:14.774479  7460 data_layer.cpp:111] Transform time: 137.565 ms.
I0203 07:50:14.924489  7460 data_layer.cpp:109] Prefetch batch: 144 ms.
I0203 07:50:14.924489  7460 data_layer.cpp:110]      Read time: 2.02807 ms.
I0203 07:50:14.924489  7460 data_layer.cpp:111] Transform time: 141.972 ms.
I0203 07:50:14.977491  7460 data_layer.cpp:109] Prefetch batch: 46 ms.
I0203 07:50:14.977491  7460 data_layer.cpp:110]      Read time: 2.13332 ms.
I0203 07:50:14.977491  7460 data_layer.cpp:111] Transform time: 43.8667 ms.
I0203 07:50:15.274508  7460 data_layer.cpp:109] Prefetch batch: 157 ms.
I0203 07:50:15.274508  7460 data_layer.cpp:110]      Read time: 39.9147 ms.
I0203 07:50:15.274508  7460 data_layer.cpp:111] Transform time: 117.085 ms.
I0203 07:50:15.423516  7460 data_layer.cpp:109] Prefetch batch: 142 ms.
I0203 07:50:15.423516  7460 data_layer.cpp:110]      Read time: 1.43788 ms.
I0203 07:50:15.423516  7460 data_layer.cpp:111] Transform time: 140.562 ms.
I0203 07:50:15.578526  7460 data_layer.cpp:109] Prefetch batch: 149 ms.
I0203 07:50:15.578526  7460 data_layer.cpp:110]      Read time: 3.22146 ms.
I0203 07:50:15.578526  7460 data_layer.cpp:111] Transform time: 145.779 ms.
I0203 07:50:15.729534  7460 data_layer.cpp:109] Prefetch batch: 144 ms.
I0203 07:50:15.729534  7460 data_layer.cpp:110]      Read time: 4.5126 ms.
I0203 07:50:15.729534  7460 data_layer.cpp:111] Transform time: 139.487 ms.
I0203 07:50:15.901545  7460 data_layer.cpp:109] Prefetch batch: 166 ms.
I0203 07:50:15.901545  7460 data_layer.cpp:110]      Read time: 6.45557 ms.
I0203 07:50:15.901545  7460 data_layer.cpp:111] Transform time: 159.544 ms.

**Comment by antran89** [comment]
Thanks @ttagu99 
How about if my batch size is 256, the benefits will be larger, right?

**Comment by ttagu99** [comment]
It depends on batch size, image size, augmentation method, gpu resource, etc.
If gpu will not always load 100% in train time, and if bottlenecks occur at prefecth batch time, it will be faster.

**Comment by antran89** [comment]
@ttagu99 Thank for the benchmark.

**Comment by antran89** [comment]
Can you try to test with new transform layer in case of training a Caffe models on multiple GPUs? In multi-ple GPUs training, Caffe also has multi-processes. I am curious about how much more parallel with additional parallel from Transform function.

**Comment by ttagu99** [comment]
My PC environment has only two 1080 GPUs. If your data augmentation function is sufficiently parallelized, it will not get any better. But if your data augmentation function is not parallelized enough, it will be faster.

**Comment by BlGene** [comment]
@ttagu99: Not to be overly discouraging, but I see  a tendency to using python for all data fetching and augmentation, see `caffe/examples/pycaffe/layers/pascal_multilabel_datalayers.py` for a basic example. I would only support this PR if you can show a significant performance difference against a reasonable attempt to do this in python -- which is unlikely.

[This](https://gist.github.com/BlGene/708190838ef0835f4c349b651bb72557) is the rough structure of what I use, in case it helps. A sensible pre-fetching python layer template that is adaptable that has been bench marked would, in my opinion, be a welcome contribution.

**Pull request closed without merging**
