### PR TITLE
Integrate clcaffe's spatial domain convolution kernel to OpenCL branch.

### PR DESCRIPTION
**Pull request by gongzg**
This is the first PR for the integration of Intel's clcaffe to this official opencl branch. This PR is mainly for some preparation and the spatial domain convolution kernel.

### CODE REVIEW

**Comment by naibaf7** [comment]
@gongzg 
Ok cool, will start reviewing and testing this weekend.

**Comment by naibaf7** [comment]
There are still a few issues, like USE_INDEX_64 = 1 will break the build. I'll fix this.

**Comment by naibaf7** [comment]
@gongzg 
I am going to merge this today. Note however the following for future PRs:
- `make lint` should return no error
- The build must work with the following configurations:
1. CUDA=1, OpenCL=1
2. CUDA=1, OpenCL=0
3. CUDA=0, OpenCL=1
- Compile-time switch compability for CUDA and OpenCL is not enough. All code must be both compile- and runtime switchable between CUDA and OpenCL (I am refering to the changes in benchmark.cpp)

**Comment by gongzg** [comment]
@naibaf7 Thanks. @listenlink we will take care of those issues in the following PRs.

**Pull request merged**
