### PR TITLE
Add Optional AudioDataLayer and LibSndFile Dependancy

### PR DESCRIPTION
**Pull request by aidangomez**
Add optional use Audio Data using the familiar functionality of Image Data.  This will allow users to import audio data in a similar manner to ImageDataLayer (text file with "<filepath> <label>\n" format) at the expense of the barebones and widely supported C library "LibSndFile".

Modifications:
- Updated make and cmake with the option USE_AUDIO (defaults to false)
- Update linter script
- Mimic ImageDataLayer for all data handling and functionality
- Added FFT utility using FFTW library
- Added spectrogram layer

Planned extensions:
- Multi-channel Audio support

### CODE REVIEW

**Comment by aidangomez** [comment]
I think the failed check may be in error. Following ImageDataLayer's lead my class defines DataLayerSetup.

**Comment by aidangomez** [comment]
Considering the relevance and importance of Audio in the machine learning field; I feel this branch is a strong first step in support and functionality. It also includes an FFT implementation similar to #544 that could easily be reapplied/extended to suit your convolutional needs in the future.

Hopefully you'll be able to provide some feedback upon my implementation and discuss what measures need to be taken for merger to happen. @longjon @shelhamer @jeffdonahue

**Comment by aidangomez** [comment]
@bhack would you also mind taking a look and advising?

**Comment by shelhamer** [comment]
Thanks for extending to a new input modality and thumbs-up for making this optional in line with #2523. We do encourage extension and use beyond vision so this is the right direction. We will try to review this soon.

**Comment by aidangomez** [comment]
@shelhamer Thanks so much, man! :smile:

**Comment by shelhamer** [comment]
Closing as better handled by a Python data layer. While I do appreciate the extension to audio, the further dependencies and amount of code make me wary. Sorry for the long wait and that my initial review didn't flag these issues.

**Pull request closed without merging**
