### PR TITLE
Add missing value support to SoftmaxLossLayer

### PR DESCRIPTION
**Pull request by longjon**
This PR adds an option, `missing_value`, which allows some specified label to indicate that loss should not be computed at the corresponding location.

This creates an issue for normalization. To match the existing normalization, we should normalize by the number of labels actually present. However, this means that the weight of each label depends on the number of missing values in each batch, which may be undesirable. For this reason an extra boolean, `normalize`, is added; if `normalize` is false, normalization occurs only over the batch size.

Ideally this would be done in a way that can be used uniformly across different loss layers, but this is the form it exists in now.

Not yet well tested.

### CODE REVIEW

**Comment by shelhamer** [comment]
Needs tests (just check loss and gradients for a toy input and truth pair) and docs, then merge.

**Comment by longjon** [comment]
I've added a doc comment describing the additional parameters, and simple tests that check the gradient with an ignore label set and with normalize set to false, so this should be ready pending any further comments.

**Comment by shelhamer** [comment]
@longjon the docs and gradient tests look good, but whether the ignored labels do not actually contribute the loss or not deserves coverage. Once that test is in, let's merge.

**Comment by longjon** [comment]
Indeed, the pure gradient checks leave something out. I've added a simple test that checks that labels are being ignored.

**Comment by shelhamer** [comment]
Thanks Jon!

**Pull request merged**
