### PR TITLE
(Dev Branch) Fix DrawNet + CMake Find ATLAS on Gentoo

### PR DESCRIPTION
**Pull request by jsupancic**
Fix Draw Net Problem (#1709) on Dev branch.
Help CMake find ATLAS on Gentoo Linux.

### CODE REVIEW

**Comment by shelhamer** [comment]
Cherry-picked the draw net fix in 1344d1b -- for CMake there is a new build in #1667 that will be merged shortly. Please follow-up there if it doesn't help with ATLAS on Gentoo.

**Comment by shelhamer** [comment]
Thanks for the fix!

**Comment by BlGene** [comment]
Quick Follow up: the cmake changes are still needed after #1667.

**Comment by jsupancic** [comment]
@BlGene  Yes, I the second patch is still required after #1667 if you want build to work out-of-the-box on Gentoo Linux.  I'm don't think have permissions to add my patch to the existing PR. How should I proceed? It's not a big deal though... it's a quick enough fix (Atlas_LAPACK_LIBRARY NAMES needs to search for atlclapack) for anyone who runs across this on Google. 

Best,
James

**Comment by shelhamer** [comment]
Thanks for the follow-up @BlGene and @jsupancic -- I've noted the need and will try to cherry-pick -- if that doesn't work I'll ask for a follow-up PR.

**Pull request closed without merging**
