### PR TITLE
Clarify batch norm parameter documentation.

### PR DESCRIPTION
**Pull request by williford**
I found the documentation for the batch norm layer in caffe.proto confusing when I was first learning how to use it. This is my attempt to make it easier to understand.

@cdoersch, would you mind giving your feedback? Also, @shaibagon and anyone else's feedback is welcome.

(Merged PR for @cdoersch's awesome batch norm implementation: #3229)

### CODE REVIEW

**Comment by cdoersch** [comment]
LGTM.  Definitely an improvement over my quick note.

**Comment by shelhamer** [comment]
Thanks for the further detail @williford!

**Comment by shaibagon** [comment]
@williford Great improvement! thank you very much!

**Comment by williford** [comment]
Thanks everyone for your quick responses!

**Pull request merged**
