### PR TITLE
Update generate_sample_data.py

### PR DESCRIPTION
**Pull request by Ashwani001**
Changed os.path.dirname(__file__) as it was returning empty...

### CODE REVIEW

**Comment by jeffdonahue** [comment]
I think it's meant to be run from the Caffe root in which case the `dirname` result should not be empty.  But making it runnable from anywhere seems fine.  Maybe declare it at the top with a name like `script_dir = os.path.dirname(os.path.abspath(__file__)` to make the code clearer and more concise though?

**Comment by Ashwani001** [comment]
That could be the reason. I probably ran it from elsewhere. Changed it to what you suggested. Does look better.

**Comment by jeffdonahue** [comment]
Thanks! Please squash to a single commit for merge.

**Comment by jeffdonahue** [comment]
Never mind -- just noticed that they each had specific and clean commit messages so I'll go ahead and merge.  Thanks @Ashwani001!

**Comment by Ashwani001** [comment]
Thanks @jeffdonahue

**Pull request merged**
