### PR TITLE
AdaDelta v2

### PR DESCRIPTION
**Pull request by kevinbache**
This is a minor update to #1122.  It brings @mohomran's AdaDelta solver into sync with modern Caffe and fixes the slow tests mentioned in #1122 by reducing the number of iterations for multi-iter tests from 500 down to 4 (as with the Nesterov tests).  All tests pass and take a normal amount of time.

### CODE REVIEW

**Comment by kevinbache** [comment]
Is there anything else that should be done for this pull request?

**Comment by shelhamer** [comment]
Thanks for carrying on #1122 and taking care of tests and examples. Could you squash all the lint commits (58c5b4c, f5485f7, 31a299a, f2b29ec, etc.) ?

**Comment by kevinbache** [comment]
No problem.  I ended up just squashing all of mine -- seemed to make the most sense.  Please let me know if there's anything else I should do!

**Comment by matthiasplappert** [comment]
I'm interested in the Ada Delta solver. Is this change likely going to make it into master anytime soon?

**Comment by shelhamer** [comment]
Carried on in #2782 -- sorry for the wait on this.

**Pull request closed without merging**
