### PR TITLE
Clear all content out of dev except README.md

### PR DESCRIPTION
**Pull request by jeffdonahue**
Not sure if this is a good idea or if this has even been an issue, but it might be clearer that dev should no longer be used or PRed to if it has nothing in it besides the README.md saying to use master.  (Obviously, all of its content and commit history can still be accessed via git.)

### CODE REVIEW

**Comment by shelhamer** [comment]
It seems there is sometimes confusion about dev still. Should this be merged to make the end of dev totally obvious?

**Comment by bhack** [comment]
Probably it is better to delete the branch now.

**Comment by lukeyeager** [comment]
I agree. Why do we care to keep the `devcommit history in this fork?

**Comment by shelhamer** [comment]
@jeffdonahue @longjon should we delete dev? All the history did make it to master in the final merge so nothing is lost. The last few PRs to dev will close but we can mark them accordingly.

Thanks for commenting @bhack and @lukeyeager.

**Comment by bhack** [comment]
All this have borderline history.

**Comment by shelhamer** [comment]
We have decided to close the last dev PRs and delete the branch to make it clear that master is the base of all development.

**Pull request closed without merging**
