### PR TITLE
Enable caffe works on system without GPU

### PR DESCRIPTION
**Pull request by shen390s**
when caffe run on system without GPU, it will raise fatal error to abort

Rongsong

### CODE REVIEW

**Comment by ajtulloch** [comment]
Compile with -DCPU_ONLY.

**Comment by shen390s** [comment]
compiled with  CPU_ONLY in Makefile.config but  still abort triggered

**Comment by shen390s** [comment]
~/workspace/rongsong/caffe.rongsong% ./examples/mnist/train_lenet.sh                 
I0710 22:28:42.116685 35693 caffe.cpp:185] Using GPUs 0
F0710 22:28:42.117197 35693 common.cpp:66] Cannot use GPU in CPU-only Caffe: check mode.
*** Check failure stack trace: ***
    @     0x10000078f1ec  google::LogMessage::Fail()
    @     0x100000791d2c  google::LogMessage::SendToLog()
    @     0x10000078ebdc  google::LogMessage::Flush()
    @     0x100000792914  google::LogMessageFatal::~LogMessageFatal()
    @     0x1000004832a8  caffe::Caffe::SetDevice()
    @         0x100160ac  train()
    @         0x10018cd0  main
    @     0x1000025b4580  generic_start_main.isra.0
    @     0x1000025b4774  __libc_start_main
    @              (nil)  (unknown)
./examples/mnist/train_lenet.sh: line 3: 35693 Aborted                 (core dumped) ./build/tools/caffe train --solver=examples/mnist/lenet_solver.prototxt

~/workspace/rongsong/caffe.rongsong% cat Makefile.config |grep -i only
# CPU-only switch (uncomment to build without GPU support).
CPU_ONLY := 1

Rongsong

**Comment by shen390s** [comment]
@ajtulloch Can you run the test to verify -DCPU_ONLY=1 will work really?

**Pull request closed without merging**
