### PR TITLE
Solver Refactor: Separate files and Change Solver's Type to String

### LINKED ISSUE #2890: Separate solvers by string type and separate source files
The `solver_type` field is a proto enum causing conflicts for concurrent development. This should be made a string as #1694 did for layer type.

The solvers are currently defined and implemented in monolithic hpp and cpp that make extension awkward. Each should be split into its own header and source.

After #2860 #2782  #2856

### PR DESCRIPTION
**Pull request by ronghanghu**
Resolve #2890.

Split `solver.cpp` into each solver per file, allow self-contained solver development, and provide abstraction for adaptive gradient solvers.

Caffe has individual cpp files for each layer, and in #1694, layer types were changed to strings to allow self-contained layer development. Similar work should be done for solvers, especially given that right now all solver implementations are in `solver.cpp` and their tests in `test_gradient_based_solver.cpp`, both 1200+ lines.

## Part 1: Solver Refactor

- [x] Split solver implementation into each file per solver, and add solver factory
- [x] Change solver type to strings, add layer-style solver factor and solver registry mechanism
- [x] Implement automatic upgrade for existing solver files
- [x] Update examples and docs

Note: **The old enum field `solver_type` is changed to the new string field `type` in `SolverParameter`. Automatic upgrade provided.**

## Part 2: Solver Abstraction (in another PR)
* Extract common parts in adaptive gradient-based solvers and provide abstract adaptive gradient solver class
* Rewrite solver tests. Split and provide abstraction for solver tests to remove duplicated code.

### CODE REVIEW

**Comment by ronghanghu** [comment]
To provide correct level of solver abstractions, I hope the hierarchy would be

    /Solver
    /Solver/GradientBasedSolver
    /Solver/GradientBasedSolver/SGDSolver
    /Solver/GradientBasedSolver/NesterovSolver
    /Solver/GradientBasedSolver/AdaptiveGradientSolver
    /Solver/GradientBasedSolver/AdaptiveGradientSolver/AdamSolver
    /Solver/GradientBasedSolver/AdaptiveGradientSolver/RMSPropSolver
    /Solver/GradientBasedSolver/AdaptiveGradientSolver/AdaGradSolver
    /Solver/GradientBasedSolver/AdaptiveGradientSolver/AdaDeltaSolver
    /Solver/HessianFreeSolver/SomeToBeImplementedHessianFreeSolver

Any suggestions are welcome!

**Comment by ronghanghu** [comment]
@shelhamer Do you prefer that I address all the above tasks in one PR, or should I split them into separate PRs (I am in favor of the latter).

**Comment by shelhamer** [comment]
@ronghanghu you are welcome to do it as a progression but certain tasks need to be done together such as

- Change solver type to strings, add layer-style solver factor and solver registry mechanism
- Implement automatic upgrade for existing solver files

so that each PR yields a correct master.

**Comment by ronghanghu** [comment]
I feel it is better to split this PR into two separate PRs, one for splitting files and one for solver abstraction. Part 1 should have be completed.

**Comment by ronghanghu** [comment]
Add rewrite solver tests to plan in this PR. The current solver tests are quite messy, which makes test failure issues like #3033 very difficult to track down.

**Comment by ronghanghu** [comment]
A rebase is needed here after #3204.

**Comment by shelhamer** [comment]
@ronghanghu sorry about that! I'm happy to do a last review and merge after the rebase so we can have orderly solver code.

**Comment by ronghanghu** [comment]
Rebased to the latest master

**Comment by shelhamer** [comment]
Thanks for splitting up the solvers and decoupling development Ronghang!

**Pull request merged**
