### PR TITLE
Add PReLULayer

### PR DESCRIPTION
**Pull request by tnarihi**
I implemented parameterized ReLU unit, which is described in http://arxiv.org/abs/1502.01852 . In my caffe fork, I tried RReLU for CIFAR10 quick examples and the performance was improved about 3%. I am happy If it is worth merging. I don't care even if it is not because I implemented it just for my purpose.

### CODE REVIEW

**Comment by pannous** [comment]
Not sure, but doesn't relu_layer already have negative_slope, which could be the same as the alpha in the paper?
** https://github.com/BVLC/caffe/blob/dev/src/caffe/layers/relu_layer.cpp

**Comment by tnarihi** [comment]
@pannous The difference between them is that 

1. slopes can be learned.
2. slopes can vary across channels.

**Comment by pannous** [comment]
I see, thanks

**Comment by tnarihi** [comment]
Modified to allow in-place computation.

**Comment by tnarihi** [comment]
Replaced by #1940

**Pull request closed without merging**
