### PR TITLE
Add Visual Studio Code files to .gitignore.

### PR DESCRIPTION
**Pull request by kyu-sz**
Using Visual Studio Code to organize the code, I find it creating a directory named ".vscode" containing files such as ".browse.VC.db", which should be ignored by Git.

### CODE REVIEW

**Comment by shelhamer** [comment]
Did you mean to submit this to the `windows` branch instead? Closing since all of the windows dev is currently happening in that branch, and not `master`.

**Comment by willyd** [comment]
@shelhamer Although as Microsoft product [Visual Studio Code](https://code.visualstudio.com/) is a cross-platform editor (I am actually using it on OS X and Windows). So it makes sense to submit this to the master branch. That being said, if submitted to the windows branch I will happily merge this.

**Comment by shelhamer** [comment]
> Although as Microsoft product Visual Studio Code is a cross-platform editor (I am actually using it on OS X and Windows). So it makes sense to submit this to the master branch.

Oh ok. I wasn't aware. If you think this is reasonable for inclusion to master, we could cherry-pick 05a9fae from this PR and merge it.

**Comment by kyu-sz** [comment]
@shelhamer Well I am using Visual Studio Code on Ubuntu (it's pretty cool), so I think it is reasonable to include this to master branch.

**Comment by willyd** [comment]
@shelhamer Sounds good to me.

**Pull request closed without merging**
