### PR TITLE
Make R-CNN the Caffe detection example

### PR DESCRIPTION
**Pull request by shelhamer**
R-CNN [1] is a state-of-the-art detector powered by a finetuned Caffe model. As an off-the-shelf example, I have made a pure Caffe version of R-CNN, ILSVRC13 detection edition, by
1. making a new model, caffe_rcnn_imagenet_model, with the RCNN class SVMs transplanted into a fully-connected layer
2. adding an R-CNN crop mode to the pycaffe `Detector`
3. rewriting our detection example, which right now runs the Caffe Reference ImageNet Model classifier on selective search windows

@rbgirshick please review to make sure that everything is clear. Thanks!
1. Rich feature hierarchies for accurate object detection and semantic segmentation. Ross Girshick, Jeff Donahue, Trevor Darrell, Jitendra Malik. CVPR 2014. Arxiv 2013.

### CODE REVIEW

**Comment by bhack** [comment]
@rbgirshick  Any plan to contribute back [FAST-RCNN](https://github.com/rbgirshick/fast-rcnn)? How [precomputed proposal](https://github.com/rbgirshick/fast-rcnn#download-pre-computed-selective-search-object-proposals) are actually generated?

**Comment by rbgirshick** [comment]
@bhack I'm happy to contribute any useful bits of Fast R-CNN to Caffe. On my side (for now at least), I need to jump through some hoops to get permission to do a PR. However, the Fast R-CNN code is all MIT licensed, so anyone can contribute it to Caffe if there's demand.

Personally, I don't think it makes sense to include all of Fast R-CNN in Caffe, but it would be nice if it worked out of the box with Caffe master. That would require merging some new layers (smooth l1, roi pooling).

Precomputed proposals used this code: https://github.com/rbgirshick/rcnn/tree/master/selective_search.

**Comment by bhack** [comment]
@rbgirshick Ok i've opened a new issue at https://github.com/BVLC/caffe/issues/2411 with a link to an evaluation of some others object proposal algorithms because I think that selective search it is still closed source.

**Comment by rbgirshick** [comment]
@bhack Use of selective search is largely for apples-to-apples comparison with previous published work. I'm going to look into using LPO (CVPR'15 paper; http://www.philkr.net/home/lpo), which has open source Python code.

**Comment by bhack** [comment]
@rbgirshick Thank you for point to LPO. I've updated the issue.

**Pull request merged**
