### PR TITLE
Fix link issue when using Homebrew OpenCV on OS X.

### PR DESCRIPTION
**Pull request by qu1j0t3**
I'm suggesting this change to the config example because it resolves the problem reported in this thread (and also experienced by myself on OS X): https://github.com/BVLC/caffe/issues/2307#issuecomment-357552138

Let me know if I should raise a specific issue in addition to this PR.

### CODE REVIEW

**Comment by Noiredd** [comment]
Thank you for the contribution.  
However, take a look just a [few lines further down](https://github.com/BVLC/caffe/blob/95d000153dc668bf86f24eb46e8982701fa7c59a/Makefile.config.example#L20-L21) the example config - there already is an option to inform Make to compile with OpenCV 3. All one needs to do is uncomment it.

**Comment by toby5box** [comment]
Yes, you are right, and I missed it.

But maybe this can still be improved:
* Should it be uncommented by default, since (I think) OpenCV version is now most likely to be 3?
* Should it be moved closer to the option enabling OpenCV?

**Comment by Noiredd** [comment]
I think most people are still on version 2, so it's better left commented.  
In my opinion it is also close enough to the `USE_OPENCV`, but if you feel that moving it above the `MDB_NOLOCK` block would improve clarity, and others agree with you by upvoting your PR - we can merge.

**Comment by toby5box** [comment]
OpenCV 3 is 2.5 years old: https://opencv.org/releases.html

Yeah, it's probably too trivial to do anything urgently about. Probably just me being unobservant. At least the issue exists for people confused by the build error, and googling.

**Pull request closed without merging**
