### PR TITLE
pytest fix: Files created with NamedTemporary files cannot be opened on Windows

### PR DESCRIPTION
**Pull request by willyd**
As the title says. This will fix the python tests when master is merged back in the windows branch. It should not impact the UNIX builds.

### CODE REVIEW

**Comment by lukeyeager** [comment]
Won't this leave a bunch of temporary files lying around?

**Comment by willyd** [comment]
@lukeyeager Yes you are right. It was late when I submitted this. I did not noticed that the other test were actually removing the files by hand. I actually don't understand why the file is removed in the first place, it should be remove only when file.close() is called not when file.flush() is. I will do some more investigation.

**Comment by willyd** [comment]
I reviewed the python docs and I think that the answer is here: https://docs.python.org/2/library/tempfile.html.

> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later)

A simple test at reopening the file created with `NamedTemporaryFile` on Windows fails with `IOError: [Errno 13] Permission denied:`. 

@lukeyeager Do you think it is acceptable (if it works) to keep the `delete=False`, replace the `self.f.flush()` with `self.f.close()` and put and `os.remove(f.name)` in the `tearDown` method?

**Comment by lukeyeager** [comment]
Well I can't speak for what the @BVLC team will want, but that's pretty much what we do in DIGITS.

**Comment by willyd** [comment]
Thanks for your feedback. I will update the PR as described and see what the core devs think of this.

**Comment by willyd** [comment]
@shelhamer If you have some time to check this out, I will soon merge the CMake build into the windows branch and after merge the latest master into it. All tests pass on appveyor except for the python tests which require this change.

**Comment by willyd** [comment]
Bump. Anyone from @BVLC can review this? This will be one less change between UNIX and Windows.

**Comment by shelhamer** [comment]
Thanks for the compatibility fix @willyd !

**Pull request merged**
