### PR TITLE
im2col with hole

### PR DESCRIPTION
**Pull request by tamakoji**
Ported algorithm of George Papandreou(DeepLab)' im2col with hole  to fit on current caffe
implementation. variable name "hole" been modified to 'kernel_stride" which make more sense than 
hole, since hole = 1 does not have hole, its just kernel stride.
modified test_im2col_kernel.cu and verified(tested test_im2col_kernel and test_im2col_layer).

### CODE REVIEW

**Comment by seanbell** [comment]
:+1:

**Comment by llllaaaa** [comment]
@tamakoji  Would you please rebase this PR with the current caffe?

**Comment by tamakoji** [comment]
@llllaaaa done.

**Comment by llllaaaa** [comment]
@tamakoji  Thanks a lot!

@shelhamer  Could you merge this into the master branch? I think it is a very useful feature

**Comment by tamakoji** [comment]
there are lots of lint errors(mostly exceeding 80chars), do I need to fix them?

**Comment by GoYchen** [comment]
@tamakoji Thank you for your works, but the code cannot run in the cudnn mode. What should I do to make the code support cudnn?

**Comment by llllaaaa** [comment]
@GoYchen  cudnn does not use im2col, and does not support holes

**Comment by GoYchen** [comment]
@llllaaaa Thank you very much for your answer.

**Comment by longjon** [comment]
This functionality is now provided by #3452.

Thanks @tamakoji for sharing this implementation!

**Pull request closed without merging**
