### PR TITLE
Add SetMinLogLevel for setting glog log level.

### PR DESCRIPTION
**Pull request by hgaiser**
As per title, this allows one to set the log level of glog logging through a function in caffe.

### CODE REVIEW

**Comment by lukeyeager** [comment]
Why are you adding a function that's never called or exposed externally?

Also, why not just set the environment variable?
```sh
export GLOG_minloglevel=2
```

**Comment by hgaiser** [comment]
What do you maan? It is exposed in caffe/common.hpp. 

I think it is much cleaner to expose such functionality through a function call than through an environment variable. I will leave it up to caffe developers to see if they agree or disagree with this perspective.

**Comment by longjon** [comment]
We can debate the merits of glog's interface, but I don't think it's a good idea to create a custom interface to a library which substitutes one line with another one line.

**Comment by hgaiser** [comment]
Fair enough, the reason I added it was because I dislike setting the environment variable and setting that flag in my code causes a linking error. My options were to link against glog or add this function in Caffe. I preferred the latter, but I will respect your opinion.

**Pull request closed without merging**
