### PR TITLE
Fix CuDNNConvolutionLayer for cuDNN v4

### PR DESCRIPTION
**Pull request by flx42**
Add a macro to check the current cuDNN version

### CODE REVIEW

**Comment by flx42** [comment]
The CMake website is under maintenance, causing the automated cmake builds to fail.
ping @shelhamer for review, it should be a quick one.

**Comment by shelhamer** [comment]
@flx42 will there be further ifdef guards for v4? If not this is simple and done. I'm happy to keep v3 compatibility and add v4 if it doesn't obscure the code. So far we have followed the current cuDNN version and dropped old versions (because of API changes).

Thanks for the PR.

**Comment by thatguymike** [comment]
This is the only change until we get to more feature support like batch normalization.  We should generally support the macro to better deal with API change-overs.

**Comment by flx42** [comment]
For v3 and v4 only, I believe you could simply replace `cudnnAddTensor` by `cudnnAddTensor_v3`. But this function is also marked as deprecated so it seems less future-proof.

**Comment by shelhamer** [comment]
Ok, agreed on the macro and this is fine as-is.

**Pull request merged**
