### PR TITLE
CNN triplet loss version with flexible triplet sets

### PR DESCRIPTION
**Pull request by Wangyida**
* Ready for a review
* Part of GSoC 2015

### CODE REVIEW

**Comment by bhack** [comment]
Hi probably the history it is still too corrupted and full of "work in progress" to be reviewed. I don't know if it his better to squash the history in a single commit or you can re-edit  you history to let review new introduced functionalities by commit. Every isolable feature you want to introduce in caffe could be reviewable as a commit. It hard to review work in progress commit, commit where you introduce something that then you remove etc. So it is better to have a single squashed commit or to reorganize the history with squashing to have very few commits strictly related to the new features you propose to introduced in caffe.

**Comment by Wangyida** [comment]
Codes are collected, the commits are the same as before, when they are squashed, it will be easier to be reviewed. @bhack

**Comment by Wangyida** [comment]
@bhack  @mtamburrano The commits are clear now, the main inappropriate act is that I used to using my master branch for development on codes and some commits are just pushed on my master branch, so when I have my development on cnn_triplet branch and have each rebase on the updated master branch, the commits on my master branch will also be restored on the new branch. I clean the commits on master branch and have a rebase again, they are tidy at last. Codes differs a lot from the beginning, So you could just have a look on whole.

**Comment by bhack** [comment]
Seems to me that you have introduced spurious changes in https://github.com/BVLC/caffe/commit/e4db1311d0d7da2da1666fc0b5cd77e06a07b076. See the diff of each file.

**Pull request closed without merging**
