### PR TITLE
libdnn: add spatial convolution implmentation

### PR DESCRIPTION
**Pull request by wzw-intel**
A new class in libdnn LibDNNConvSpatial which is porting
from clcaffe's ConvolutionLayerSpatial class but with following
changes:
 - Use basic kernel as benchmark kernel
 - Add LibDNNConvConfig::phase_test to indicate using in TEST phase

### CODE REVIEW

**Comment by wzw-intel** [comment]
@naibaf7 @gongzg
Please help to review this pull request for libdnn

**Comment by naibaf7** [comment]
@wzw-intel Scheduled for review as discussed.

**Comment by naibaf7** [comment]
So ok, this doesn't fully adhere to the LibDNN format yet, i.e. kernel generation is not embedded. Consequently, because the standalone LibDNN does not do kernel resource embedding, this won't work in the standalone.

**Comment by wzw-intel** [comment]
@naibaf7 Thanks for your comments. I will refine the kernel source and make it more reusable and tuneable. Considering that the spatial convolution kernel is heavy dependent on the cl_intel_subgroups extension, it may not reproduce the same performance on another hardware, so we may not put a lot of efforts on supporting other hardware for now.

**Comment by naibaf7** [comment]
Yes, but if we write the kernel source like the original LibDNNConv class does, then it might be possible to reuse the code modularly also on other hardware (skipping cl_intel_subgroup).
However I do know this is not strongly in your interest. But at least otherwise, the Intel spatial kernel implementation inside LibDNN needs to be independent of other Caffe components (such as kernel code embedding) so that I am able to pull it into the standalone library.

**Comment by wzw-intel** [comment]
Sure, I will make an embedded version that has no dependence on Caffe components.

**Comment by naibaf7** [comment]
Great :) after that it should only take about 1-2 weeks until it's available in the standalone.

**Comment by wzw-intel** [comment]
@naibaf7  @gongzg
New version for LibDNNConvSpatial. This version make the kernel source embedded into host code and some refine for kernel source. Please help review, thanks.

**Comment by naibaf7** [comment]
Ok, I'll check the implementation.

**Comment by wzw-intel** [comment]
There is no backward implementation in this version, since currently we just focused on inference.

**Comment by naibaf7** [comment]
Should I adapt it to work with the LibDNN fused convolution backward pass? Like that, inference would be done with LibDNN-IntelSpatial and backward pass would still work.

**Comment by wzw-intel** [comment]
Great:) nice to have it.

**Comment by naibaf7** [comment]
Ok, it will be ready and merged on approx. the 27th of April.

**Comment by naibaf7** [comment]
@wzw-intel Postponed after NIPS deadline, sorry.

**Comment by naibaf7** [comment]
@wzw-intel @gongzg please review the merge. I cleaned up some unnecessary variables and fixed a few other things. Next step should be replacing the normal Caffe Intel Spatial layer with the new implementation.

**Comment by wzw-intel** [comment]
@naibaf7 Reviewed, very nice refining. 

For "replacing the normal Caffe Intel Spatial layer with the new implementation.", do you mean that we need to add a new subclass (i.e. LibDNNConvolutionSpatialLayer) of class ConvolutionLayer by using LibDNN? 

Another question is when we use "ConvolutionParameter_Engine_LIBDNN", which one do we choose as default convolution layer? LibDNNConvolutionLayer or LibDNNConvolutionSpatialLayer?

**Comment by naibaf7** [comment]
@wzw-intel We could, for now, just pick LibDNNConvolutionSpatialLayer with the LIBDNN engine if we see that it is an Intel GPU, and otherwise use the LibDNNConvolutionLayer.

And you are correct, it needs a LibDNNConvolutionSpatialLayer. When that works we can remove the old spatial convolution layer.

Glad that you like the refining.

**Pull request merged**
