### PR TITLE
Exposing solver callbacks to python

### PR DESCRIPTION
**Pull request by philkr**
This PR exposes the solver callbacks to python. They can be added by calling ```solver.add_callback(on_start, on_gradient)```, where ```on_start``` and ```on_gradient``` are python functions.

### CODE REVIEW

**Comment by jeffdaily** [comment]
+1

This is a great addition.  Code is elegant.  Please accept this pull request.

**Comment by seanbell** [comment]
@longjon @shelhamer thoughts?

**Comment by jeffdonahue** [comment]
`Solver_addCallback` should maybe be spelled `Solver_add_callback` for consistency with e.g. `BlobVec_add_blob`.  Otherwise LGTM.

**Comment by jeffdonahue** [comment]
All LGTM now. Thanks @philkr!

**Comment by kli-nlpr** [comment]
Any examples how to use this?

**Comment by shaibagon** [comment]
A simple and nice example can be found [at this SO thread](http://stackoverflow.com/a/41667083/1714410).

**Pull request merged**
