### PR TITLE
add default value to rms_decay and fix documentation

### LINKED ISSUE #3472: rms_decay's default value not set
According to the documentation, the default value for rms_decay is 0.02, yet in caffe.proto file its default value is not define. Either the documentation should be changed to reflect this (i.e., write "recommended value" instead of "default value"), or change caffe.proto's default value to match the documentation.

### LINKED ISSUE #3930: RMSProp solver is different from the one described on the tutorial page?
I find the RMSProp solver code is different from the RMSProp algorithm that is described in the Caffe tutorial page (http://caffe.berkeleyvision.org/tutorial/solver.html).

Actually I think they are very different. The tutorial page describe the RMSProp algorithm as:

(vt)i={(vt−1)i+δ,(vt−1)i⋅(1−δ),(∇L(Wt))i(∇L(Wt−1))i>0else
(vt)i={(vt−1)i+δ,(∇L(Wt))i(∇L(Wt−1))i>0(vt−1)i⋅(1−δ),else
(Wt+1)i=(Wt)i−α(vt)i,
(Wt+1)i=(Wt)i−α(vt)i,
If the gradient updates results in oscillations the gradient is reduced by times 1−δ1−δ. Otherwise it will be increased by δδ. The default value of δδ (rms_decay) is set to δ=0.02δ=0.02.

But the RMSProp implementation is:
CUDA_KERNEL_LOOP(i, N) {
    float gi = g[i];
    float hi = h[i] = rms_decay*h[i] + (1-rms_decay)*gi*gi;
    g[i] = local_rate * g[i] / (sqrt(hi) + delta);
  }

Which one is the true RMSProp algorithm?

### PR DESCRIPTION
**Pull request by alicanb**
fixes #3472 and fixes #3930

### CODE REVIEW

**Comment by alicanb** [comment]
@jeffdonahue would you mind taking a look? People are writing redundant issues and PRs regarding this...

**Comment by lukeyeager** [comment]
So I should close https://github.com/BVLC/caffe/pull/4567, then?

**Comment by alicanb** [comment]
@lukeyeager Yep

**Comment by jeffdonahue** [comment]
Thanks @alicanb, this seems right to me. (It's definitely bad that this defaults to 0 now, didn't realize that...)

**Pull request merged**
