### PR TITLE
Added Cmake Support to VS 2017 (and its RC)

### PR DESCRIPTION
**Pull request by PENGUINLIONG**
This pull request added CMake support to recently released Visual Studio 2017 RC (and VS 2017 in the future).

### CODE REVIEW

**Comment by willyd** [comment]
We would need to download to make sure that CMake downloads the right precompiled libraries too. Since VS 2017 and VS 2015 are supposed to be binary compatible no need to have a different set of libraries just download the VS 2015 ones. See https://github.com/BVLC/caffe/blob/windows/cmake/WindowsDownloadPrebuiltDependencies.cmake.

**Comment by PENGUINLIONG** [comment]
Noticed that. CMake was unable to find Boost libs and OpenCV because of their naming convention. But all the dependencies are, of course, binary compatible. Renaming is an acceptable solution.

However, another thing should be paid attention is that the MSVC executable is moved from `/path/to/vs/VC/bin` to `/path/to/vs/VC/Tools/MSVC/14.10.24728/bin/HostX64/x64`. The generation of cuda objects will also be affected. Manual replacement is required again because the `FindCUDA.cmake` provide by CMake 3.7.2 is buggy, check it out at line 487.

**Comment by willyd** [comment]
> Noticed that. CMake was unable to find Boost libs and OpenCV because of their naming convention. But all the dependencies are, of course, binary compatible. Renaming is an acceptable solution.

Good catch. I did not think about that. 

> However, another thing should be paid attention is that the MSVC executable is moved from /path/to/vs/VC/bin to /path/to/vs/VC/Tools/MSVC/14.10.24728/bin/HostX64/x64. The generation of cuda objects will also be affected. Manual replacement is required again because the FindCUDA.cmake provide by CMake 3.7.2 is buggy, check it out at line 487.

This is an upstream CMake issue. I guess we should wait until CMake fixes this before integrating this change then. You will hit some problems with CUDA and MSVC 2017 compatibility as well. VS 2015 is now supported by CUDA 8 but was not in 7.5. I guess we will have to wait for 8.5?

**Comment by PENGUINLIONG** [comment]
Sure. It depends on a lot of things. Let this closed first.

**Pull request closed without merging**
