### PR TITLE
Output accuracies per class.

### PR DESCRIPTION
**Pull request by rmanor**

### CODE REVIEW

**Comment by rmanor** [comment]
Hi, I refactored the change.
Now it will output per class accuracies in the second top blob, if exists.

**Comment by rmanor** [comment]
ping? Thanks.

**Comment by bhack** [comment]
@rmanor Can you wait forever?

**Comment by rmanor** [comment]
@bhack  What?
I didn't know how to update this PR so I'm going to start a new one synced to master.

**Comment by bhack** [comment]
OK I think that you was tired to waiting for a review

**Comment by rmanor** [comment]
Yeah, but I thought I give it another try before giving up :)

**Comment by rmanor** [comment]
Replaced this with https://github.com/BVLC/caffe/pull/2935

**Pull request closed without merging**
