### PR TITLE
Matcaffe2

### PR DESCRIPTION
**Pull request by shelhamer**
This PR resurrects #501. The good work started by @sguada will be finished by @bharath272 and @s-gupta who have a lot of MATLAB and Caffe experience.

### CODE REVIEW

**Comment by shelhamer** [comment]
Note that @jeffdonahue has a potential patch for N-D blobs in matcaffe: https://github.com/BVLC/caffe/pull/1970#issuecomment-76645769. That will be brought in here rather than #1970.

**Comment by sguada** [comment]
Thanks for helping out with this @bharath272 and @s-gupta if you have questions let me know.

**Comment by bearpaw** [comment]
Does this version of Matlab interface support training a model (Perform forward and then update the model weights by performing backward)?

**Comment by johnny5550822** [comment]
When will matcaffe2 be out in master branch?

**Comment by shelhamer** [comment]
Replaced by the MATLAB revolution of #2505 (merged to master). Thanks @sguada for your original work in bringing matcaffe closer to pycaffe.

**Pull request closed without merging**
