### PR TITLE
Updated relighting augmentation by yanii

### PR DESCRIPTION
**Pull request by dfagnan**
This is an attempt at an updated pull request on the relighting augmentation work done by @yanii in #1865. I'm happy to perform any remaining steps in order to have this reviewed. I think this an important feature that really needs to make it into master. Testing for my own examples has reduced over-fitting significantly.

### CODE REVIEW

**Comment by mtamburrano** [comment]
I've not tried this augmentation yet, but I'm interested on this PR

**Comment by hyojinie** [comment]
Has anyone tested this code? Can I directly use it in current version of Caffe or the version right before?

Also, why is "repeated float eigen_value = 8;"  instead of 3?

**Comment by yxchng** [comment]
@hyojinie have u tried? Does this work? Also are you able to calculate PCA for the entire imagenet dataset? My computer is not sufficient to calculate PCA for such a large dataset. If you have, can you share the result? Thanks.

**Comment by hyojinie** [comment]
It does work. I subsampled images in my training set to compute PCA.

**Pull request closed without merging**
