### PR TITLE
check embed index in debug mode

### PR DESCRIPTION
**Pull request by twmht**
checking embed index should be enabled in non-debug mode.

### CODE REVIEW

**Comment by Noiredd** [comment]
I will copy your findings from the issue #6268 to start the conversation:

> when input contains a negative padding value, the kernel function in the embed layer may have undefined behavior.
it's hard to debug, since embed layer in gpu mode does not check the valid values for input. However, it does not fail on the embed layer but on other part of cuda code (like cudaCheckEvent in the Timer).
in cpu mode, it only checks the valid values in debug mode.

However, my opinion is that this is what the debug mode is for. By default (in release) we focus on performance and do not make any checks during propagation. In case of problems the scenario is to fallback to the debug mode and check what's going on - so in a way, this PR breaks this workflow.

**Comment by twmht** [comment]
@Noiredd 

I see.

**Comment by twmht** [comment]
@Noiredd 

But why not add DCHECK utility in kernel function of Embed layer?

If I fall back to Debug Mode, it's still hard to debug. Since it would not fail on embed layer but on the other part of cuda API.

**Comment by Noiredd** [comment]
Debugging or safeguarding GPU code is not straightforward: kernels (GPU functions) cannot execute host (CPU) code, so any DCHECK placed there will fail the compilation. In situations like this, I think one is supposed to not only fall back to debug but also CPU mode.  
Perhaps a check could be added behind `#ifdef DEBUG`, for example by running a special debug kernel before the actual `EmbedForward` kernel?

I think this PR should be open, if only to discuss potential solutions (and hear other's opinions).

**Comment by twmht** [comment]
@Noiredd 

Adding `#ifdef DEBUG` is a good idea.

I may update this PR in a few days.

thanks.

**Comment by twmht** [comment]
@Noiredd 

I have updated this PR, and it works in debug mode.

If I have negative index or other unaccepted index, then the outputs can correctly tell me what is wrong, this is the same behavior when running in cpu mode.

Here is the output

```
src/caffe/layers/embed_layer.cu:19: void caffe::EmbedForward(int, const Dtype *, const Dtype *, int, int, int, Dtype *) [with Dtype = float]: block: [1765,0,0], thread: [251,0,0] Assertion `index >= 0` failed.
src/caffe/layers/embed_layer.cu:19: void caffe::EmbedForward(int, const Dtype *, const Dtype *, int, int, int, Dtype *) [with Dtype = float]: block: [1765,0,0], thread: [252,0,0] Assertion `index >= 0` failed.
src/caffe/layers/embed_layer.cu:19: void caffe::EmbedForward(int, const Dtype *, const Dtype *, int, int, int, Dtype *) [with Dtype = float]: block: [1765,0,0], thread: [253,0,0] Assertion `index >= 0` failed.
src/caffe/layers/embed_layer.cu:19: void caffe::EmbedForward(int, const Dtype *, const Dtype *, int, int, int, Dtype *) [with Dtype = float]: block: [1765,0,0], thread: [254,0,0] Assertion `index >= 0` failed.
src/caffe/layers/embed_layer.cu:19: void caffe::EmbedForward(int, const Dtype *, const Dtype *, int, int, int, Dtype *) [with Dtype = float]: block: [1765,0,0], thread: [255,0,0] Assertion `index >= 0` failed.
F0323 22:00:47.647169 14711 syncedmem.hpp:39] Check failed: error == cudaSuccess (59 vs. 0)  device-side assert triggered
*** Check failure stack trace: ***
    @     0x7f79ce3045cd  google::LogMessage::Fail()
    @     0x7f79ce306433  google::LogMessage::SendToLog()
    @     0x7f79ce30415b  google::LogMessage::Flush()
    @     0x7f79ce306e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f79cebc6c24  caffe::CaffeFreeHost()
    @     0x7f79cebc5da0  caffe::SyncedMemory::~SyncedMemory()
    @     0x7f79ceadf609  boost::checked_delete<>()
    @     0x7f79ceadf9f4  boost::detail::sp_counted_impl_p<>::dispose()
    @           0x41ff4a  boost::detail::sp_counted_base::release()
    @           0x41ffdd  boost::detail::shared_count::~shared_count()
    @     0x7f79ceaddd5e  boost::shared_ptr<>::~shared_ptr()
    @     0x7f79ceade262  boost::shared_ptr<>::operator=()
    @     0x7f79cead1dc6  caffe::Blob<>::ShareData()
    @     0x7f79cec2f82a  caffe::Net<>::ShareWeights()
    @     0x7f79cec6e413  caffe::RecurrentLayer<>::Forward_gpu()
    @           0x422606  caffe::Layer<>::Forward()
    @     0x7f79cec2ebfb  caffe::Net<>::ForwardFromTo()
    @     0x7f79cec2e863  caffe::Net<>::Forward()
    @     0x7f79cec21332  caffe::Solver<>::Test()
    @     0x7f79cec2103e  caffe::Solver<>::TestAll()
    @     0x7f79cec1f916  caffe::Solver<>::Step()
    @     0x7f79cec1f407  caffe::Solver<>::Solve()
    @           0x41cba9  train()
    @           0x41ef31  main
    @     0x7f79cca9a830  __libc_start_main
    @           0x41b4b9  _start
    @              (nil)  (unknown)

```

**Comment by Noiredd** [comment]
This is a reasonable solution -- thank you @twmht

**Pull request merged**
