### PR TITLE
Import bash completion script for caffe from Debian Package.

### PR DESCRIPTION
**Pull request by CDLuminate**
Imported from Debian Package caffe (1.0.0~rc3+20160715-g42cd785-2).

### CODE REVIEW

**Comment by CDLuminate** [comment]
This pull request closes issue: https://github.com/BVLC/caffe/issues/3149

Debian packaging repo can be found here:

https://anonscm.debian.org/cgit/debian-science/packages/caffe.git/

**Comment by lukeyeager** [comment]
Can we combine this with https://github.com/BVLC/caffe/pull/4237 to install the completion in the appropriate place with CMake?

How do we install it manually (https://github.com/BVLC/caffe/issues/3149#issue-109763459)? Can you document how to install it somewhere? Maybe as a comment in the header?

**Comment by CDLuminate** [comment]
Installing path:

The recommended way is to install it into system directory e.g. `/usr/share/bash-completion/completions/` but this requires super user privilege.

Manual installing
```
$ sudo cp caffe /usr/share/bash-completion/completions/
$ .bashrc # reload completion scripts if enabled
```

**Comment by shelhamer** [comment]
Thanks for the completion @CDLuminate !

**Pull request merged**
