### PR TITLE
Refactored solvers with fluent pattern

### PR DESCRIPTION
**Pull request by nakosung**
I refactored solvers with fluent pattern to add a solver like rmsprop, which isn't included in this PR. After merging this PR, rmsprop will be proposed.

A cool thing introduced by this PR is keeping code DRY(Do not Repeat Yourself). You don't have to write similar code paths for cpu/gpu.

Modified ADAGRAD solver is like below:
```
op
      // compute square of gradient in update
      .sqr(param, update)
      // update history
      .add(update,history,history)
      // prepare update
      .sqrt(history,update)
      .add_scalar(delta,update)
      .div(param,update,update)      
      // scale and copy
      .axpby(local_rate,update,Dtype(0),param)
```

### CODE REVIEW

**Comment by nakosung** [comment]
Some tests are failed due to 'different trained weights'. It may not be an 'failure' because I've changed pow into sqr/sqrt, which can drive weights different. If maintainers decide to merge this PR, I'll update test cases.

**Comment by jeffdonahue** [comment]
This is a cool concept, but I'm not sure we want to adopt a new pattern to unify the math interface specifically for the solvers, as opposed to a more general unification at the level of the math interface itself, as in the device abstraction effort (#610, which should be restored eventually...).  Maybe there are some interesting ideas here that could complement that effort though?

**Comment by jeffdonahue** [comment]
(Sorry, didn't mean to immediately close...)

**Comment by shelhamer** [comment]
Agreed that this is a neat concept, but it's perhaps too local when done only for the solver. 

Re: RMSprop, it is a solver that is on our TODO list so we'd welcome a PR for it.

**Comment by sguada** [comment]
It would be better if it were part of Blob so it could be used in the
layers.

Sergio

2015-01-21 19:07 GMT-08:00 Evan Shelhamer <notifications@github.com>:

**Comment by nakosung** [comment]
In fact I had implemented RMSprop in this pattern(fluent), PR for RMSprop should be re-written in the orginal caffe style.

**Comment by nakosung** [comment]
Applying this pattern to whole program will not be a hard thing.

**Comment by shelhamer** [comment]
@nakosung please PR RMSprop in the current Caffe style first. Once that is in, we can figure out a plan for the fluent style in Caffe. Thanks for both the consideration of how to make the Caffe code more readable and concise.

**Comment by nakosung** [comment]
@shelhamer Okay, I'll try to PR RMSprop in a separate branch, but for now it doesn't have a priority.

**Pull request closed without merging**
