### PR TITLE
Cuda/Blas array

### PR DESCRIPTION
**Pull request by philkr**
This is a basic implementation of CPU/GPU array class for caffe. It overloads basic element-wise operations (+,-,/,*,minimum,maximum,log,exp,...) it an easier to use interface that the current blas/cublas functions. For most parts it completely hides the underlying GPU/CPU interface, so you no longer have to write duplicate code for the two. It also works for both C++ and Python (see test_array.py for a python example).

Currently it is based on the SyncedMemory and can bind to any existing SyncedMemory, such as Blob data or diff. In terms of speed it's not much slower than the current blas functions, but not as fast as custom kernels, such as thrust lambda functions. If there is an interest in merging this, there are some more features we should add:
- [ ] Reductions such as (sum, min/max, ...) both along single dimensions and over the entire array
- [ ] Specialized expression evaluation for common functions (such as axpy, ...)

Sorry, this is kind of a large PR, and would probably take some work to merge. Please let me know if there is a general interest in the community to add this feature.

If you want to see the array class in action, you can look at my array based solver branch: https://github.com/philkr/caffe/tree/array_solver . It makes writing new solvers much easier without having to worry about CPU or GPU functions.

### CODE REVIEW

**Comment by futurely** [comment]
Would you like to have a look at the design in #2586? By replacing the underlying data structure of Blob with SyncedTensor which has hight level math API, developers will be able to get rid of calling low level blas functions directly. A bigger benefit is that most layers will only have to be implemented in a single version instead of both CPU and GPU versions right now.

**Comment by philkr** [comment]
I completely agree that caffe should have an array or tensor class, with
basic math primitives. I'm not sure if replacing SyncedMemory is a bit too
radical. I feel if someone really wants to use blas they should. It would
also be nice to have the array interfere minimally with the rest of caffe,
in the beginning.
Another thing which might help win people over is that and array might
actually have the potential of being faster than blas for operations like
a*x+b*y, as those could be optimised and executed in a single kernel
instead of 2 blas calls...

**Comment by futurely** [comment]
Both this PR and #2585 could be parts of the [refactoring blueprints](http://tutorial.caffe.berkeleyvision.org/caffe-cvpr15-improving.pdf) of @Yangqing.

The number one priority of the design of #2585 is backward compatibiity and not to break any code that already works. Please note that all the existing APIs are kept intact and all the unit tests pass as usual which means that all the existing applications built with Caffe have to do nothing to adopt the new API. The developers are free to choose the old plain BLAS and the new tensor API.

**Comment by futurely** [comment]
Speaking of operators, [DMLC's Minerva provides some examples](https://github.com/dmlc/minerva/tree/master/minerva/op).

**Comment by shelhamer** [comment]
Closing since Caffe never took the all-knowing, all-doing array/tensor direction.

**Pull request closed without merging**
