### PR TITLE
Opencl - replace deprecated method call in prelu layer backwards_gpu()

### PR DESCRIPTION
**Pull request by vpa1977**
While developing a 3d convnet I've noticed that prelu layer implementation uses a deprecated offset() method. Replaced it with a "modern" vector-based one.

### CODE REVIEW

**Comment by naibaf7** [comment]
Ok, needs reviewing. Thanks.

**Comment by naibaf7** [comment]
Does not work, runtests failed.

**Comment by vpa1977** [comment]
Thanks, I'll look into it.

**Comment by naibaf7** [comment]
It is rolled back. Please make sure these tests return without issue before the next PR:
`make lint -j4`
`make runtest -j4`
or if runtest has issues and aborts: `/build/test/test_all.testbin --gtest_filter=*LU* 1`

**Pull request merged**
