### PR TITLE
Fix typo in solver.md

### PR DESCRIPTION
**Pull request by bamos**

### CODE REVIEW

**Comment by longjon** [comment]
Thanks for the fix, but you've misspelled Nesterov... can you force push the correct version?

**Comment by bamos** [comment]
Hi @longjon - fixed in newest commit.

**Comment by longjon** [comment]
Thanks, but ideally could you squash these commits into one (e.g., `git rebase -i`, or use `git push -f`)? No need to have an extra typo in our history...

**Comment by shelhamer** [comment]
At any rate, this is fixed in 648aed7.

I'd like to give a shout-out to `git rebase --autosquash` for cleaning up work.

**Pull request closed without merging**
