### PR TITLE
Make IO dependencies optional (leveldb lmdb snappy hdf5 opencv)

### PR DESCRIPTION
**Pull request by cypof**
It's probably not what you want to do in the long run, but it's simple and fits the use case of embedding Caffe in another framework. That's by far the most important aspect of dependency management for us and probably a lot of people. As you suggested last week data can be processed externally and provided through the memory_data_layer.

The cmake build would need to get updated, I can look at it if you are interested to merge this.

### CODE REVIEW

**Comment by futurely** [comment]
The omnipotent `NO_IO_DEPENDENCIES` is simpler than but not as flexible as the macros used in #1074 to manage each of the libraries independently. #1738 proposed to also improve CMake scripts.

**Comment by cypof** [comment]
Closing, probably not that useful outside of our use case.

**Comment by shelhamer** [comment]
There is actually interest in having a barebones Caffe without all the IO, so I'll leave this open for now so that it's more visible. While granular switches are the ideal, this all-or-nothing switch might be useful for some in the meantime.

**Comment by shelhamer** [comment]
Closing as replaced by #2523 but thanks for pioneering this.

**Pull request closed without merging**
