### PR TITLE
Fixed RPATH for python and tools cmake scripts.

### PR DESCRIPTION
**Pull request by BlGene**
These changes were necessary to get the new cmake ( #1667)  scripts to work on my system.
@Nerei @shelhamer

### CODE REVIEW

**Comment by Nerei** [comment]
But this PR breaks examples with build-tree. Give me some time, I'll take look more precisely a bit later and suggest how to solve this.

**Comment by Nerei** [comment]
@BlGene  (CC: @shelhamer)

I took couple hours before I realized where is the bug :-) Explanation is here: https://github.com/BVLC/caffe/pull/1939. Please take a look if this patch fixes your problems. One more proof that to write something in source folder (symlink in this case) is a very bad practice.

**Comment by Nerei** [comment]
@BlGene Please don't forget to clean install-tree before testing.

**Comment by BlGene** [comment]
This is fixed by @Nerei  in a more elegant way in PR #1939.

**Comment by shelhamer** [comment]
Thanks for the initial fix @BlGene and follow-up @Nerei.

**Pull request closed without merging**
