### PR TITLE
python: PEP8; changed docstring documentation style to NumPyDoc style

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by longjon** [comment]
Thanks, I like it! @shelhamer, I think you wrote many of the docstrings here; does this look good to you?

**Comment by shelhamer** [comment]
Yeah, I like this too. I only chose "give" and "take" for their knuckle tattoo style and my ignorance of the NumPyDoc format. Thanks @MartinThoma!

**Comment by MartinThoma** [comment]
Wow, that was quick! Thanks for merging :-)

**Comment by bhack** [comment]
It is the routine here :)

**Pull request merged**
