### PR TITLE
Test for Snapshot and Restore in Solver

### PR DESCRIPTION
**Pull request by prateekbs**
I have written some preliminary code to test Snapshot and Restore in the Solver. However, it wrecks the current interfaces by converting Snapshot, SnapshotSolverState and RestoreSolverState from protected members to public members. 

Is testing non public code frowned upon? If the answer to the previous question is no, then how do I go about testing protected members?

### CODE REVIEW

**Comment by flx42** [comment]
Be careful, your indentation is totally messed up. Don't use tabs, use 2 spaces.

**Comment by prateekbs** [comment]
@flx42: Thanks for the heads up. I fixed the indentation.

**Comment by jyegerlehner** [comment]
> Is testing non public code frowned upon? If the answer to the previous question is no, then how do I go about testing protected members?

When there is a need to access protected or private members for test purposes, the technique I've usually seen used is to create a trivial subclass of the class you are trying to test, e.g. SolverForTest, in the test code which exposes public accessors to the protected members of the base class. Then run the test against that subclass. That way the "real" class keeps its members protected, but they can still be accessed in the test.

**Comment by prateekbs** [comment]
@jyegerlehner: Thanks.

**Comment by shelhamer** [comment]
Closing for the interference in the interface, but thanks for the testing effort.

**Pull request closed without merging**
