### PR TITLE
fix the bug in db_lmdb.cpp 

### PR DESCRIPTION
**Pull request by kgl-prml**
I wrote a program to transfer my csv file to lmdb format using db:DB and db::Transaction defined in db.hpp and db_lmdb.hpp. And I encountered a strange error. I doubt if there exists a bug in the db:Transaction definition.

In db_lmdb.cpp: 
line72:  `int put_rc = mdb_put(mdb_txn, mdb_dbi, &mdb_key, &mdb_data, 0);`
line 84: `MDB_CHECK(mdb_txn_commit(mdb_txn));`

My result shows that `mdb_put` succeed (i.e. `put_rc = 0`) and `mdb_txn_commit` failed and throws a `MDB_MAP_FULL` error. （i.e. error code is -30792).

So for my case, in the `void LMDBTransaction::Commit()`, it thinks the map size is enough (i.e. `put_rc=0`), however `mdb_txn_commit` failed because of `MDB_MAP_FULL`.
Furthermore, the current LMDB map size is 4M only.

Part of the log information is listed as follows:
```
I0509 17:29:54.469671 103125 db_lmdb.cpp:101] Doubling LMDB map size to 4MB ...
I0509 17:29:54.471114 103125 convert_csv_data.cpp:120] Processed 72000 files.
I0509 17:29:54.476613 103125 convert_csv_data.cpp:120] Processed 73000 files.
I0509 17:29:54.482061 103125 convert_csv_data.cpp:120] Processed 74000 files.
I0509 17:29:54.487568 103125 convert_csv_data.cpp:120] Processed 75000 files.
I0509 17:29:54.493044 103125 convert_csv_data.cpp:120] Processed 76000 files.
I0509 17:29:54.498538 103125 convert_csv_data.cpp:120] Processed 77000 files.
I0509 17:29:54.503990 103125 convert_csv_data.cpp:120] Processed 78000 files.
I0509 17:29:54.509546 103125 convert_csv_data.cpp:120] Processed 79000 files.
... ...
I0509 17:29:54.860395 103125 convert_csv_data.cpp:120] Processed 143000 files.
I0509 17:29:54.865814 103125 convert_csv_data.cpp:120] Processed 144000 files.
F0509 17:29:54.870347 103125 db_lmdb.hpp:15] Check failed: mdb_status == 0 (-30792 vs. 0) MDB_MAP_FULL: Environment mapsize limit reached
*** Check failure stack trace: ***
    @     0x2b7090d72b5d  google::LogMessage::Fail()
    @     0x2b7090d76b77  google::LogMessage::SendToLog()
    @     0x2b7090d749f9  google::LogMessage::Flush()
    @     0x2b7090d74cfd  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b708aa562c4  caffe::db::MDB_CHECK()
    @     0x2b708aa56054  caffe::db::LMDBTransaction::Commit()
    @           0x408013  convert_dataset()
    @           0x408548  main
    @       0x3d49a1ed5d  (unknown)
    @           0x407709  (unknown)
Aborted (core dumped)
```

So I think using the returning code of `mdb_put` may not be enough to judge if the map size is sufficient. We should also check the status of `mdb_txn_commit` to decide if we need to double the map size.

You may reproduce the error using the program and data in the attachment.
[convert_csv_data.zip](https://github.com/BVLC/caffe/files/254718/convert_csv_data.zip)

### CODE REVIEW

**Comment by seanbell** [comment]
@lukeyeager

**Comment by lukeyeager** [comment]
> You may reproduce the error using the program and data in the attachment.
> convert_csv_data.zip

I can't open that zipfile.

**Comment by kgl-prml** [comment]
> I can't open that zipfile.
How about this one ?
[convert_csv_data.zip](https://github.com/BVLC/caffe/files/255688/convert_csv_data.zip)

I have verified #4117 , and it works now. :)

**Comment by shelhamer** [comment]
Thanks for the report @kgl-prml!

**Pull request closed without merging**
