### PR TITLE
Implement the triplet ranking hinge loss layer

### PR DESCRIPTION
**Pull request by kloudkl**
The triplet ranking hinge loss plays an important role in the deep ranking network of Google (#578). The major reference for the loss function is [1].

Compared with the Weighted Approximate Rank Pairwise (WARP) loss layer (#257, #126, #88), this loss is much simpler.

[1] Mohammad Norouzi, David Fleet, and Ruslan Salakhutdinov. Hamming Distance Metric Learning. NIPS 2013.

### CODE REVIEW

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by windyting0331** [comment]
hi, I have read the code of the test cases for triple ranking loss and found that it checks the gradient of (*bottom)[0] ,but bottom[0] is the cpu diff of query data. In the backward function, you do not compute the diff of query data, so it may be always 0.  Is there anything wrong?

**Comment by shelhamer** [comment]
Closed as abandoned -- feel free to rescue if interested since a ranking loss could be useful.

**Pull request closed without merging**
