### PR TITLE
Added artifacts to appveyor builds

### PR DESCRIPTION
**Pull request by willyd**
Adding artifacts will make it easier for newcomers to get started with caffe by downloading pre-built binaries.

This PR also adds some checks in the build_win.cmd script.

### CODE REVIEW

**Comment by benediktvanmegen** [comment]
Hey willyd,
i got stucked with the Introduction:
when i want to execute the  command `scripts\build_win.cmd` it says:
_Traceback (most recent call last):
  File "C:\Users\pai-t\Desktop\caffe\caffe versuch4\caffe\scripts\\download_prebuilt_dependencies.py", line 11, in <module>
    from six.moves import urllib
ModuleNotFoundError: No module named 'six'
ERROR: Downloading dependencies failed_

Can you help me? Cheers

**Comment by willyd** [comment]
@benediktvanmegen You solved the first problem correctly. The second one is due to the fact that I built the dependencies with either Python 2.7 or 3.5. Boost.Python links against Python so it is best to avoid mixing Python versions. I suggest that you either replace python 3.6 with 3.5 or built the dependencies yourself using [caffe-builder](https://github.com/willyd/caffe-builder). If you choose to uninstall 3.6 and install 3.5 I suggest that you install [Anaconda](https://www.continuum.io/downloads#windows).

**Comment by benediktvanmegen** [comment]
@willyd Yes, you were right. I installed python 3.6 first and added to my `Path`. After that i installed Anaconda 2.7 and also added to my `Path`. 
No i delete both `path`s and installed python 2.6. I was able to executed the scripts\build_win.cmd with 
_0 errors_ but
_500 warnings_

Ok, i will ignore the warnings and go on with the introductioin.

**Comment by benediktvanmegen** [comment]
ok, iam not sure if it works correctly.
I am able to execute the caffe.exe but when i type into the cmd:
`caffe test`
_caffe.exe_ crashes (is not working anymore)
do i need a model or something?
it says:
`caffe <command> <args>` // what does args mean?

I also open VS 2015 and a build a solution of the caffe.sln:
After a little Time i got:
Debug x64: _========== Rebuild All: 23 succeeded, 0 failed, 4 skipped ==========_ 

Release x64: _========== Build: 19 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========_
with the message:
_Unable to start program C:\...\caffe\build\x64\ALL_BUILD 
Access denied_


Is everything right?

**Comment by willyd** [comment]
> Now i delete both paths and installed python 2.6.

Python 2.6 is not supported either. You need 2.7 or 3.5. I just works by chance.

> ok, iam not sure if it works correctly.
> I am able to execute the caffe.exe but when i type into the cmd:
> caffe test
> caffe.exe crashes (is not working anymore)
> do i need a model or something?
> it says:
> caffe <command> <args> // what does args mean?

Yes you need to provide the paths to your prototxt files and other command line switches such as gpu and stuff.

> Debug x64: ========== Rebuild All: 23 succeeded, 0 failed, 4 skipped ==========
> 
> Release x64: ========== Build: 19 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========
> with the message:
> Unable to start program C:...\caffe\build\x64\ALL_BUILD
> Access denied
> 
> Is everything right?

You cannot debug ALL_BUILD. You need to debug the caffe.exe project.

Questions like these should be asked on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/. Please ask your question to one of these places.

Please take any discussion there if you have more questions.

**Pull request merged**
