### PR TITLE
NV changed path to cudnn

### PR DESCRIPTION
**Pull request by cypof**

### CODE REVIEW

**Comment by shelhamer** [comment]
Looks reasonable. @lukeyeager can you confirm this is the desired new path? (Thanks for your help with Travis, as always.)

**Comment by lukeyeager** [comment]
Yep, that's exactly the change I'm about to make for the DIGITS documentation, too:
https://github.com/NVIDIA/DIGITS/pull/1075/files

**Comment by lukeyeager** [comment]
Merged something similar to our fork: https://github.com/NVIDIA/caffe/pull/248.

**Comment by shelhamer** [comment]
👍

**Pull request merged**
