### PR TITLE
Caffe-opencl for Windows

### PR DESCRIPTION
**Pull request by SHEKOLDA**
Hi, so this PR is not a completely working solution and is made primarily as to simplify code comparison and get some advice on how to make caffe-opencl work on Windows.

My idea of doing that was to straightfowardly mash up two branches, basing on the windows one since it's building without problem for me on Windows. I added the necessary files (layers needed for greentea and libdnn, cmake modules), excluded those that contradict and modified some(cmakelists and common files like 'blob', 'common', etc.). I left everything that has to do with tests, cuda, matlab support and examples untouched for now.

I was able to build this modified version without using cuda, fft and intel-spatial (although it required adding by hand some of the include directories (namely opencl and viennacl) and some linker inputs). I also excluded some of the .cl kernels (spatial conv and fft) for now since they were causing some trouble when converted to cl_kernels.cpp (string was too long). I wasn't yet able to properly test out the results, but caffe command line interface seems to be working allright, while pycaffe doesn't. When trying to import _caffe.pyd I get the `ImportError: DLL load failed` error, followed by a bunch of random symbols.

So I would appreciate some help because I have almost no clue of what to do next, while possibly missing something obvious. Thanks.

P.S.: also this is my first PR as well as first time uploading anything to github so I might have done something incredibly stupid and will be glad to correct that if pointed out.

### CODE REVIEW

**Comment by naibaf7** [comment]
Ok cool. So obviously there are many changes that should not happen.
But I think we can make this work. I'll have a look at the CMake differences.

**Comment by willyd** [comment]
This is great news! 

This error:

> ImportError: DLL load failed

Might be due to missing DLLs on your path. Have you executed the prependpat.bat file that is bundled with the pre-built dependencies?

**Comment by SHEKOLDA** [comment]
@willyd 
Yeah I executed it and it didn't help. I believe the problem is in generating _caffe.pyd. Maybe something wrong with encoding or idk.

**Comment by SHEKOLDA** [comment]
@willyd 
Nevermind, I forgot to add opencv DLLs to path. It's allright now.

**Comment by SHEKOLDA** [comment]
@naibaf7 
Well there seems to be a problem compiling kernels as I get:

> ViennaCL: FATAL ERROR: Could not find kernel 'fillbuffer_float' from program 'kernel_program'
Number of kernels in program: 0

error. I couldn't follow your advice from https://github.com/BVLC/caffe/issues/4188 since I didn't build testbin, so I guess I'll need to figure out how to build tests properly before delving into this problem.

**Comment by naibaf7** [comment]
@SHEKOLDA 
Yes correctly. You could however post first what the `device_query` gives out!
```
/build/tools/caffe.bin device_query
```

**Comment by SHEKOLDA** [comment]
@naibaf7 
Yeah right

> I1115 12:43:33.412132 10208 common.cpp:382] Total devices: 4
I1115 12:43:33.412132 10208 common.cpp:383] CUDA devices: 0
I1115 12:43:33.412132 10208 common.cpp:384] OpenCL devices: 4
I1115 12:43:33.412132 10208 common.cpp:408] Device id:                     0
I1115 12:43:33.412132 10208 common.cpp:410] Device backend:                OpenCL
I1115 12:43:33.412132 10208 common.cpp:412] Backend details:               Intel(R) Corporation: OpenCL 1.2
I1115 12:43:33.412132 10208 common.cpp:414] Device vendor:                 Intel(R) Corporation
I1115 12:43:33.412132 10208 common.cpp:416] Name:                          Intel(R) HD Graphics 4400
I1115 12:43:33.412132 10208 common.cpp:418] Total global memory:           1708759450
I1115 12:43:33.412132 10208 common.cpp:408] Device id:                     1
I1115 12:43:33.412132 10208 common.cpp:410] Device backend:                OpenCL
I1115 12:43:33.412132 10208 common.cpp:412] Backend details:               Intel(R) Corporation: OpenCL 1.2
I1115 12:43:33.412132 10208 common.cpp:414] Device vendor:                 Intel(R) Corporation
I1115 12:43:33.412132 10208 common.cpp:416] Name:                          Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
I1115 12:43:33.412132 10208 common.cpp:418] Total global memory:           8465113088
I1115 12:43:33.412132 10208 common.cpp:408] Device id:                     2
I1115 12:43:33.412132 10208 common.cpp:410] Device backend:                OpenCL
I1115 12:43:33.427736 10208 common.cpp:412] Backend details:               Advanced Micro Devices, Inc.: OpenCL 2.0 AMD-APP (1912.5)
I1115 12:43:33.427736 10208 common.cpp:414] Device vendor:                 Advanced Micro Devices, Inc.
I1115 12:43:33.427736 10208 common.cpp:416] Name:                          Capeverde
I1115 12:43:33.427736 10208 common.cpp:418] Total global memory:           2147483648
I1115 12:43:33.427736 10208 common.cpp:408] Device id:                     3
I1115 12:43:33.427736 10208 common.cpp:410] Device backend:                OpenCL
I1115 12:43:33.427736 10208 common.cpp:412] Backend details:               Advanced Micro Devices, Inc.: OpenCL 2.0 AMD-APP (1912.5)
I1115 12:43:33.427736 10208 common.cpp:414] Device vendor:                 GenuineIntel
I1115 12:43:33.427736 10208 common.cpp:416] Name:                          Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz
I1115 12:43:33.427736 10208 common.cpp:418] Total global memory:           8465113088

I tried setting different devices but the outcome is mostly the same, although with devices 0 and 1 scaffolding the net is notably slower and also gives a bunch of additional lines: 

> 0x000000001E08E14C (0x0000000000000000 0x0000000000000002 0x000000000CFDEAC8 0x000000001E0A4DF6), PyObject_Call() + 0x6C bytes(s)
0x000000001E114ACB (0x0000000000000002 0x0000000000000002 0x00000000035F4D80 0x00000000005EF798), PyEval_GetGlobals() + 0x13B bytes(s)
0x000000001E115392 (0x0000000000000000 0x0000000000000083 0x0000000001116788 0x000000000000006A), PyEval_GetGlobals() + 0xA02 bytes(s)
0x000000001E118B04 (0x000000000CE76B58 0x0000000000000002 0x0000000000000001 0x0000000000000000), PyEval_EvalFrameEx() + 0x3704 bytes(s)
0x000000001E113988 (0x0000000000000002 0x0000000000000002 0x000000000B451898 0x000000001E0C615A), PyEval_GetFuncDesc() + 0x158 bytes(s)
0x000000001E11537C (0x0000000000000000 0x0000000000000083 0x0000000001313038 0x000000000000006A), PyEval_GetGlobals() + 0x9EC bytes(s)
0x000000001E118B04 (0x000000000CFB4648 0x000000000B44C920 0x0000000000000001 0x0000000000000000), PyEval_EvalFrameEx() + 0x3704 bytes(s)
0x000000001E11A3A2 (0x00000000012DE830 0x0000000000000003 0x000000000B44C920 0x000000005FB0C600), PyEval_EvalCodeEx() + 0x7E2 bytes(s)
0x000000001E1139F9 (0x0000000000000003 0x0000000000000007 0x000000000B451978 0x000000001E0C6106), PyEval_GetFuncDesc() + 0x1C9 bytes(s)
0x000000001E11537C (0x0000000000000000 0x0000000000000083 0x0000000001313038 0x000000000000006A), PyEval_GetGlobals() + 0x9EC bytes(s)
0x000000001E118B04 (0x0000000001322048 0x0000000000643D27 0x0000000000000001 0x0000000000000000), PyEval_EvalFrameEx() + 0x3704 bytes(s)
0x000000001E11A3A2 (0x00000000012DE430 0x000000005FA8F904 0x00000000012DE430 0x000000000119CAC0), PyEval_EvalCodeEx() + 0x7E2 bytes(s)
0x000000001E11A439 (0x000000005FB0C660 0x0000000000643D27 0x0000000001137268 0x0000000001137268), PyEval_EvalCode() + 0x29 bytes(s)
0x000000001E1472AA (0x000000005FB0C660 0x000000000129BC48 0x0000000000000001 0x000000001E146AAE), PyErr_Display() + 0x41A bytes(s)
0x000000001E14859A (0x0000000000643D27 0x0000000001136228 0x0000000001137268 0x0000000001136330), PyRun_FileExFlags() + 0xAA bytes(s)
0x000000001E148BF0 (0x0000000000000001 0x0000000000643D27 0x000000005FB0C660 0x00000000005EFF38), PyRun_SimpleFileExFlags() + 0x1C0 bytes(s)
0x000000001E149583 (0x0000000000643D00 0x0000000000000001 0x0000000000000000 0x0000000000643D27), PyRun_AnyFileExFlags() + 0x63 bytes(s)
0x000000001E0452B0 (0x0000000000000000 0x0000002A00000000 0x0000000000000000 0x0000000000000000), Py_Main() + 0x9D0 bytes(s)
0x000000001D00119E (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF889348364 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF88BDE5E91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
0x00007FF88BDE5E91 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)

**Comment by SHEKOLDA** [comment]
@naibaf7 
So ok, I built tests and ran `test_all.testbin --gtest_filter=*OpenCLKernelCompileTest* 2` and all tests passed although for some reason before starting tests it prints out code of all kernels.

**Comment by SHEKOLDA** [comment]
@naibaf7 
Oh yeah when running all the tests it fails with the following:

> [----------] 3 tests from BatchNormLayerTest/2, where TypeParam = struct caffe::GPUDevice<float>
[ RUN      ] BatchNormLayerTest/2.TestForward
ViennaCL: FATAL ERROR: Could not find kernel 'fillbuffer_float' from program 'kernel_program'
Number of kernels in program: 0

**Comment by naibaf7** [comment]
That's very odd. I will need to try this out myself when I have time.

**Comment by SHEKOLDA** [comment]
@naibaf7 
Indeed it does hint, I didn't notice that at first:

> Build Status = -2 ( Err = -11 )
Log: "C:\Users\User\AppData\Local\Temp\OCL2460T1.cl", line 34: warning: OpenCL
          extension is now part of core
  #pragma OPENCL EXTENSION cl_khr_fp64 : enable
"C:\Users\User\AppData\Local\Temp\OCL2460T1.cl", line 52: warning:
          unrecognized #pragma
  #pragma OPENCL_EXTENSION cl_khr_global_int32_base_atomics : enable
"C:\Users\User\AppData\Local\Temp\OCL2460T1.cl", line 245: warning: variable
          "out" was declared but never referenced
    Dtype out = arg;
"C:\Users\User\AppData\Local\Temp\OCL2460T1.cl", line 2512: error: function
          "softmax_loss_backward_float" has already been defined
  __kernel void TEMPLATE(softmax_loss_backward,Dtype)(const int_tp nthreads,
"C:\Users\User\AppData\Local\Temp\OCL2460T1.cl", line 2841: warning: variable
          "out" was declared but never referenced
    Dtype out = arg;
"C:\Users\User\AppData\Local\Temp\OCL2460T1.cl", line 5108: error: function
          "softmax_loss_backward_double" has already been defined
  __kernel void TEMPLATE(softmax_loss_backward,Dtype)(const int_tp nthreads,
2 errors detected in the compilation of "C:\Users\User\AppData\Local\Temp\OCL2460T1.cl".
Frontend phase failed compilation.

**Comment by SHEKOLDA** [comment]
@naibaf7 
@willyd 
So I'm guessing the reason is loss_layers.hpp which I copied from opencl branch and which isn't present in caffe-windows and the stuff from this header is defined elsewhere. Could you help me track down duplicate code, some idea where/what to look for?

**Comment by naibaf7** [comment]
@SHEKOLDA 
That would be weird. Loss layers is also present in the current master branch:
https://github.com/BVLC/caffe/blob/master/include/caffe/layers/loss_layer.hpp

**Comment by SHEKOLDA** [comment]
@naibaf7 
Not `include/caffe/layers/loss_layer.hpp` but `include/caffe/loss_layers.hpp`. They are both present in opencl branch, while the latter is absent from both master and windows.

Nonetheless, good point. I'll try doing it the other way around and tell about results.

**Comment by SHEKOLDA** [comment]
@naibaf7 
Oh I've found what was causing that. My bad, I forgot to remove kenrels I made for Faster R-CNN and there was a mistake. Now the error doesn't appear. Although tests still stop at the same test but without error. Simply stop.

**Comment by SHEKOLDA** [comment]
@naibaf7 
I tried running other tests that follow BatchNormLayerTest, they all fail at SomethingLayerTest/2 if they have this. SomethingLayerTest/0 and /1 run allrigth. Not sure if that means anything. It doen't seem to be the problem with tests specifically, because it fails without error in the same manner when simply trying to run caffe.

**Comment by naibaf7** [comment]
@SHEKOLDA 
SomethingLayerTest/0 and /1 are usually on the CPU. /2 is GPU single precision and /3 is GPU double precision.

**Comment by willyd** [comment]
@naibaf7 the windows branch is 5 commits behind master.

@SHEKOLDA Are you building a static or shared library? Tests will fail with a shared library. I might give this a shot to help out next week, let me know when you port the windows files to the opencl branch and push it back to this PR.

Things to be aware of when building on windows:

- Build a static library
- The windows CMake build will generate a header file forcing consuming projects to link in the layers and solvers object files. 
- Don't mix VS versions: precompiled binaries must use the same version you want to build caffe with.

**Comment by SHEKOLDA** [comment]
@willyd 
I'm building static libraries, yes. All the GPU tests don't simply fail, they fail to run. Maybe something with my overall configuration so would be helpful if you try it out. And I've already updated the PR to be based on opencl branch. Thanks.

**Comment by willyd** [comment]
@SHEKOLDA Can you give me a list of links of things I need to install? I am on Windows 10.

**Comment by SHEKOLDA** [comment]
@willyd 
Yeah you'll need to build ViennaCL and install some OpenCL SDK. That's pretty much it in addition to the usual dependencies. 

https://sourceforge.net/projects/viennacl/ here's ViennaCL.

As for Intel SDK I'm not sure myself what to download but it should be pretty easy to find.

**Comment by naibaf7** [comment]
@willyd 
Should be enough to have the nVidia drivers and the latest ViennaCL from GIT (https://github.com/viennacl/viennacl-dev). Intel OpenCL SDK and AMD APP SDK are optional if you want more compiler options for your onboard GPU and CPU.

**Comment by naibaf7** [comment]
This has been fixed.

**Pull request closed without merging**
