### PR TITLE
Added CHECK if loss is NaN

### PR DESCRIPTION
**Pull request by sguada**
As mentioned in #1349 If Loss is Nan it doesn't make sense to keep training.

### CODE REVIEW

**Comment by seanbell** [comment]
More generally, perhaps this should die on any loss that isn't finite (i.e. NaN, +infinity, or -infinity).

**Comment by PiranjaF** [comment]
Thanks a lot - this is highly needed! I've spent way too long trying to understand why pycaffe was crashing when the network was diverging. Quite annoying when trying to do a parameter search over a large parameter space.

**Comment by PiranjaF** [comment]
How would I go about stopping training more silently? With this implementation any script in pycaffe would still crash immediately. It should be possible to catch the error or perhaps set as an option that training stops without stopping everything else.

**Comment by seanbell** [comment]
@PiranjaF you could change it to break from the loop instead of crash.

**Comment by PiranjaF** [comment]
@seanbell I did not think it could be done that easily. Thanks.

**Comment by shelhamer** [comment]
Closing since the dev branch is deprecated. Please send PRs to master.

**Pull request closed without merging**
