### PR TITLE
"weights" added to solver parameters, "snapshot_prefix" field default initialization

### PR DESCRIPTION
**Pull request by IlyaOvodov**
This pull request implements parts 1&2 of feature request #6110.

"weights" parameter is added to SolverParameters class. It has quite the same meaning as "--weights" command line parameter of caffe executable and is used if "--weights" command line parameter is not specified. It makes it possible to specify initial weights in a solver.prototxt file instead of command line and make it unnecessary to change command line or command file.

It is aimed to make it possible to localize all training parameters in a solver.prototxt file. See #6110 for more detailed motivation.

If a "--snapshot" command line parameter is specified, new "weights" parameter in a solver.prototxt file is ignored. So there is no need to modify this file to continue previously interrupted training process from a snapshot.

EDIT by @Noiredd: second important contribution of this PR is a default initialization of the "solver_prefix" parameter. Previously Caffe would fail on parsing the solver if a snapshot was requested but no prefix given.

### CODE REVIEW

**Comment by Noiredd** [comment]
I will review this today/tomorrow. In the meantime, please [squash](https://github.com/BVLC/caffe/wiki/Contributing#2-squashing-commits) your commits to maintain a simpler history.

If you want to keep all changes related to #6110 in this PR (which would be great IMO), I would suggest having one commit for each point. This would make review much easier.

**Comment by IlyaOvodov** [comment]
Thank you! I am not shure it's a good idea to keep all changes related to #6110 in this one PR because 1) they are absolutely independent and 2) I'm not shure that I'll have possibility to implement al them at once. So shep-by-step approach looks better.
But I realized that it is worth adding python support of "weights" property to SolverParams to this PR, so I ask to wait with review until I'll do it as well as I'll squash commits (sorry, my fauls).

**Comment by IlyaOvodov** [comment]
I've squashed commits i this PR. I've found that python support of specific "weights" property is quite useless until python interface to solver will be improved in total. So this PR looks to be completed and ready for review. 
But some tests failed with messages like these:
W: The repository 'http://dl.google.com/linux/chrome/deb stable Release' does not have a Release file.
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/39x/InRelease  Unexpected type excepted 21 != 5
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
It seems it is not connected

**Comment by IlyaOvodov** [comment]
Along the way I've added implementation of improvement No.2 from issue #6110.
Now this PR is fully completed.

**Comment by IlyaOvodov** [comment]
@Noiredd , I agree with your idea and decided that to make appropriate changes is better than to discuss it.
Modifications are squashed to the 1st commit here.

**Comment by Noiredd** [comment]
Looks good. Thank you for the improvement, @IlyaOvodov!

**Comment by IlyaOvodov** [comment]
> compiling would give error like:

There are these 2 reasons:
1. You didn't update caffe.proto file. Check that you have line  "repeated string weights = 42; " (https://github.com/BVLC/caffe/pull/6123/commits/c32629435a1e5dacc8a90a309d8b255d7b629379#diff-e0bd8d028edf0f88febfebe3bf703904R253) in it
2. You didn't fully rebuild the project, so that caffe.proto  file was not recompiled.

**Pull request merged**
