### PR TITLE
Crop layer remove redundance

### PR DESCRIPTION
**Pull request by xmyqsh**
remove the redundancy for loop in crop.cpp
remove the redundancy compute in crop.cu

### CODE REVIEW

**Comment by williford** [comment]
The change in the crop_layer.cpp file looks good to me. The code was in a for-loop when it does the same thing every loop (index is used and nothing is incremented).

I haven't figured out how the crop_layer.cu changes are equivalent yet. Can you give some explanation?

**Comment by xmyqsh** [comment]
@williford   glad to see you interesting my PR
case 
`    const int lines = top[0]->shape(cur_dim);`
`    const int height = top[0]->shape(cur_dim);`
so 
`lines` is equal to `height`
from 
`__global__ void copy_kernel(const int n, const int height, const int width,`
`copy_kernel<<<CAFFE_GET_BLOCKS(lines), CAFFE_CUDA_NUM_THREADS>>>(
            lines, height, width,`
we know `n` is equal to `lines`
from 
`CUDA_KERNEL_LOOP(index, n) {`
we know `index` is less than `n` 
so `index` is also less than `height`
so `index / height` is always zero
and `index % height` is always `index`

so 
`int src_start = index / height * src_outer_stride
                   + index % height * src_inner_stride;`
is equivalent to
`int src_start = index * src_inner_stride;`

these simplicity can remove `N*C*H*2` times  division, multiply, mod and add operations in one forward or backwark process

**Comment by shelhamer** [comment]
@BlGene could you take a look when you have the chance?

**Comment by BlGene** [comment]
It makes sense that we don't need to iterate over the size of the last spatial dimension because we are copying it in one go, as it is stored in memory continuously. 

Sorry for overlooking this before.


@xmyqsh: Thanks for finding this, can you please squash the PR.
@shelhamer: This looks correct to me.

**Comment by shelhamer** [comment]
Thanks @xmyqsh for the simplification and removal of the redundant operations.

**Pull request merged**
