### PR TITLE
Make the two separate build systems clearer in the documentation

### PR DESCRIPTION
**Pull request by keir**

### CODE REVIEW

**Comment by bhack** [comment]
Or probably remove Makefile. Two build system are quite impossible to be maintained in sync. Also Travis builds are not aligned between Make and Cmake.

**Comment by keir** [comment]
I had some trouble getting Caffe built since the installation instructions were not easily scannable, hence this patch. Is the documentation out of date with practice (e.g. is CMake the new official system)? I suggest merging this as-is since it's a strict improvement. If the Make system is deprecated, then that is a separate change.

**Comment by bhack** [comment]
Yes is it ok. But it is not really clear how this two build systems are in sync.

**Comment by keir** [comment]
OK. So can you merge it? Or should I abandon this?

**Comment by bhack** [comment]
@keir All core devs are MIA. We need to wait some celestial sign.

**Comment by keir** [comment]
Ah, I didn't realize you were not a core dev :) They may be finishing off their ICCV reviews.

**Comment by jeffdonahue** [comment]
Thanks for improving these docs @keir -- merged in 6d11108 with a typo fix.

**Pull request closed without merging**
